iotaledger/iri

src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/dto/AbstractResponse.java, src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java, src/test/java/com/iota/iri/APIIntegrationTests.java
Minor change to nodeInfo command to also return the jre version.  The intent is to provide a bit more info when troubleshooting nodes (mostly other people's) who are having issues.  It's also a way to get my feet wet a bit with IRI.
=> Add jre version to node info

src/main/java/com/iota/iri/hash/PearlDiver.java, src/main/java/com/iota/iri/service/API.java
Tests with attachToTangle for a bundle with 4 txs showed the following situation:
In 7 of 21 cases, one of the 4 nonces was returned as 999999999...
PearlDiver.search() has an IN-OUT-argument. Tracing proved that the the transactionTrits are calculated correctly - for the fault nonces as well - but after return from search(), when using the trits for building the transaction object, the nonce is 999999999... This happens most frequently when the spam loop is active and then a concurrent call to attachToTangle is made.
A further problem is created by the missing join() within the PearDiver thread structure. The worker threads have a chance to continue running when they should terminate because the creator does not care to wait for their termination.
=> Threading issues in PearlDiver.java

src/main/java/com/iota/iri/Milestone.java
The "Latest Milestone Tracker" misses counting new milestones in the case where the bundle is not complete in the first attempt. The milestone is then marked as 'analyzed' and no retry is attempted.
=> Fix 'milestone not counted' because of missing bundle.

src/main/java/com/iota/iri/service/API.java
When using --remote-limit-api option, there was no check to confirm the source, so it just performed a pure API limitation. These changes introduced allow source address-based limiting.
=> Fix remote api limit to allow localhost

src/main/java/com/iota/iri/hash/Curl.java
Should be more efficient on most JREs.
=> Use Arrays.fill to reset

src/main/java/com/iota/iri/IXI.java
This bug should fix https://github.com/iotaledger/iri/issues/182
Root cause: When files are edited, Java creates at least two or more WatchKey events of type MODIFY. One for editing the file content and one for modifying the timestamp of the file.
Fix: Comparing the latest modified time of the file with the current timestamp of the file. It should be greater than 50 milliseconds, otherwise we're omitting the handling request.
=> Fixed double WatchKey event bug

Dockerfile
alpine version didn't work
```Exception in thread "main" java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni2898419474021443955.so: Error loading shared library libstdc++.so.6: No such file or directory (needed by /tmp/librocksdbjni2898419474021443955.so)```
=> replace java alpine to openjdk-jre version

.travis.yml, src/main/java/com/iota/iri/controllers/TransactionViewModel.java
Update didn't ensure to include the obsoleteTag previously. This fixes that.
=> Updated TransactionViewModel.java update function

src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/dto/GetBalancesResponse.java
This is a reasonable step toward safe zero-confirmation bundle promoting spends.
The client would query this to test if it can spend from a subtangle not yet checkpointed by a milestone.
=> Added functionality to check balance by tip

src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/network/Node.java
modifies Node caches from LRU to FIFO, 
with additional probabilistic drop cache entry - `P_DROP_CACHE_ENTRY`.
fixes #428 - credit does to @Pomyk that found the bug and offered a workaround (#455)!
this fixes the issue where storing a transaction would fail, but the "recently seen" cache would still hold a copy.
the difference from #455 is that the probabilistic solution has a much smaller memory and comp. footprint.
so not harming the common case, while still allowing the cache to refresh itself and recover from the rare case of failed store.
=> allows "recently seen" caches to forget failed transaction stores

README.md
- Appended --dns-resolution-false Command line option description to the readme.
=> add --dns-resolution-false flag to readme.

src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/network/Neighbor.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/network/TCPNeighbor.java, src/main/java/com/iota/iri/network/UDPNeighbor.java, src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java, src/main/java/com/iota/iri/service/API.java
These 2 components, NewTransactionLimit for neighbors & API calls, were added to IRI and disabled by default.
however, they require more research and testing before making it to the reference implementation.
=> revert NEW_TX_LIMIT and API_NEW_TX_LIMIT

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/network/Node.java
based on #435 ,
this allows reattaching old transactions from a previous epoch.
in addition, transactions with a timestamp in far future will also be filtered.
=> Feature: attachment timestamp filter

src/main/java/com/iota/iri/LedgerValidator.java
`Snapshot.isConsistent` check is executed on `latestSnapshot.patchedDiff(currentState)` which means that the current snapshot is patched w/ the `currentState`, which is the result of `getLatestDiff`.
however, `getLatestDiff` result is effected by `visitedHashes` - stopping traversal if hash already visited. so the related `diff` needs to be applied as well:
currently: `snapshot -> getLatestDiff`
PR: `snapshot -> diff -> getLatestDiff`
=> updateDiff - check consistency on currentState including diff

src/main/java/com/iota/iri/service/TipsManager.java
The unlocking already happens in the getTransactionsToApproveStatement, line 619 in API.java. A fail here would try to double-unlock, causing this cryptic error.
=> Fixes #534

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/zmq/MessageQ.java
zeromq is not thread safe to use.
Hence, the Socket should only be used from within one thread.
=> zmq: only write to socket from one thread

.github/issue_template.md, .github/pull_request_template.md, README.md, src/main/java/com/iota/iri/LedgerValidator.java, src/main/java/com/iota/iri/Milestone.java, src/main/java/com/iota/iri/controllers/MilestoneViewModel.java, src/main/java/com/iota/iri/controllers/StateDiffViewModel.java
LedgerValidator initializes wrong consistent milestone after restart when node is not fully synced.
When node is synced to solid milestone X and latest milestone is Y, after restart solid milestone is incorrectly initialized to Z (usually very close to Y).
Method LedgerValidator.buildSnapshot() is responsible for building the most recent consistent milestone. It uses MilestoneViewModel.firstWithSnapshot() and MilestoneViewModel.nextWithSnapshot() to iterate on every milestone with snapshot then gets the state differences and patches them to the current snapshot. These methods deterministically rely on StateDiffViewModel.exists() which internally uses tangle.maybeHas(). The problem is that tangle.maybeHas() can only guarantee when entry is not present, but does not guarantee if entry is …
=> Solid Milestone initialization fix

src/main/java/com/iota/iri/storage/ZmqPublishProvider.java
- Publish the trytes of a transaction to the ZMQ for dapp purposes.
- Refactored ZmqPublishProvider to reduce nesting and separate concerns. 
- Using StringBuilder instead of StringBuffer because it is more efficient and is guaranteed to be thread-safe in this context.
=> Publish the trytes of a transaction to the ZMQ

src/main/java/com/iota/iri/IRI.java
adds a `--zmq-enable` flag to enable ZMQ via CLI
Fixes # https://iotaledger.atlassian.net/browse/IRI-27
- manual test of launching with and without the flag, and reading the ZMQ feed.
=> allow enabling ZMQ via CLI flags

src/main/java/com/iota/iri/service/API.java
When creating private testnets we don't want to read the previous spent addresses file from the mainnet.
So when we are in testnet mode `previousEpochsSpentAddresses.txt` file is ignored.
Fixes https://iotaledger.atlassian.net/browse/IRI-26
IRI was ran with `--testnet` flag. The file was skipped.
=> IRI-329 ⁃ `readPreviousEpochsSpentAddresses` should only run on mainnet

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/network/replicator/Replicator.java, src/main/java/com/iota/iri/network/replicator/ReplicatorSinkPool.java, src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java
This fixes a regression in #610 - `TRANSACTION_PACKET_SIZE` was replaced by `REQUEST_HASH_SIZE` in TCP replicators.
- used git bisect to find where TCP stopped working
- tested syncing a local node with and without the fix.
=> fix TRANSACTION_PACKET_SIZE assignment to TCP replicators

src/main/java/com/iota/iri/hash/Kerl.java, src/test/java/com/iota/iri/hash/KerlTest.java
`Kerl.absorb(...)` now 666% faster, plus cleaner and simplified code ! I'm exaggerating a little, it is actually only 665.55% faster. 
Snapshot.initial loading is now 👍 315% faster. 👍 
Big time hog was **bigIntFromTrits(...)**. Everything else in Kerl.java was very fast already.
- Created a fast track for Radix power multiplication.
- Created a native math routine to munch 40 trits at a time into the main math routine.
- Added test to ensure that there is no math overflow.
Reusable instance state removed since it complicates reading the code and offers no performance advantages. All state now method-local.
As per @th0br0  suggestion, I compared to alternate implementation [jota...kerl](https://github.com/iotaledger/iota.lib.java/blob/master/jota/src/main/java/jota/pow/Kerl.java) 
- My …
=> Kerl.java absorb now 😈 666% faster 😈 - plus 🍦 cleaner and 🍦 simplified code

src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/conf/Configuration.java
In order to run private testnets it is useful to be able to control the db folder.
The `--testnet` flag has overriden user configs from ini file and disabled this option.
So a flag for a custom folder was added AND the overriding behavior of the ini is now gone.
https://iotaledger.atlassian.net/browse/IRI-25
IRI was ran with flag and modified ini file.
=> Check ini file before loading default testnet values and add testnetdb flag

src/main/java/com/iota/iri/hash/PearlDiver.java
See https://github.com/iotaledger/iri/issues/732
(0) Changed
OLD  `numberOfThreads = Math.max(Runtime.getRuntime().availableProcessors() - 1, 1)`
NEW `numberOfThreads = Math.max(1, Math.min(6, numberOfThreads - 1))` 
(as per charted performance over many thread counts.)
(1) Removed unnecessary wait conditions and notifyAll: Thread.join will automatically return since CANCELLED will terminate all loops and end all workers.
(2) Removed unnecessary sync on RUNNING at start.
(3) moved some same-line variable declarations to newlines for clarity.
(4) Removed unnecessary code blocks in Switch statements.
(5) Subbed in HIGHBITS and LOWBITS in second switch statement (consistent with first switch statement)
(6) Line 162 (old) 152 (new), put mask condition in WHILE condition instead of floating at …
=> Pearl driver optimal threading

src/main/java/com/iota/iri/hash/PearlDiver.java
BUG FIX
```
int available = Runtime.getRuntime().availableProcessors();
numberOfThreads = Math.max(1, Math.floorDiv(available * 8, 10));
```
=> [urgent bug fix] PearlDiver - Inserted check for number of available processors.

src/main/java/com/iota/iri/service/API.java
tips body param of getBalances is unusable due to a trailing space.
Fixes #768 
Bug fix (a non-breaking change which fixes an issue)
Integration test with the IOTA C++ Library.
=> Remove trailing space in getBalances tips body param

src/main/java/com/iota/iri/service/API.java
fix MAX_TIMESTAMP_VALUE to actually represent "max positive 27-trits value"
Fixes #531 
Manually checking the value of this field in the Debugger,
testing conversion of `3812798742493` to trytes: `MMMMMMMMM` (thanks to https://laurencetennant.com/iota-tools/)
=> fix MAX_TIMESTAMP_VALUE to actually represent "max positive 27-trits value"

pom.xml, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/model/Hash.java, src/main/java/com/iota/iri/model/HashId.java, src/main/java/com/iota/iri/model/HashPrefix.java, src/main/java/com/iota/iri/service/tipselection/EntryPointSelector.java, src/main/java/com/iota/iri/service/tipselection/RatingCalculator.java, src/main/java/com/iota/iri/service/tipselection/TailFinder.java, src/main/java/com/iota/iri/service/tipselection/TipSelector.java, src/main/java/com/iota/iri/service/tipselection/WalkValidator.java, src/main/java/com/iota/iri/service/tipselection/Walker.java, src/main/java/com/iota/iri/service/tipselection/impl/CumulativeWeightCalculator.java, src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/RatingOne.java, src/main/java/com/iota/iri/service/tipselection/impl/TailFinderImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkerAlpha.java, src/main/java/com/iota/iri/utils/collections/impl/TransformingBoundedHashSet.java, src/main/java/com/iota/iri/utils/collections/impl/TransformingMap.java, src/main/java/com/iota/iri/utils/collections/interfaces/UnIterableMap.java, src/test/java/com/iota/iri/TransactionTestUtils.java, src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java, src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightCalculatorTest.java, src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/RatingOneTest.java, src/test/java/com/iota/iri/service/tipselection/impl/TailFinderImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkerAlphaTest.java
Rework of the Tip Selection algorithm, to better match the IOTA whitepaper
This is a complete rewrite of the tip selection algorithm in IRI,
Entry point selection, rating calculation, and walkers.
*This PR only introduces the code - the integration and clean up of `TipsManager` is a separate PR.
Main features:
1. Cumulative weights are used (as opposed to an estimated calculation).
1. `exp(alpha * Hy)` transition function from the IOTA whitepaper (as opposed to `Hy^(-3)` estimation)
1. Walkers don't stop at an invalid transaction but ignore them instead.
1. Code organization for better readability and maintainability
Fixes #774 #770 #771
- Unit tests
- Local testnets
- Running canaries on the mainnet
- Metrics collection using …
=> Rework of the Tip Selection algorithm, to better match the IOTA whitepaper

.travis.yml
Testnet db files are now in an S3 bucket and should be removed from the github repo.
Fixes #647 
Travis test passed
=> download testnet Db files from S3

src/main/java/com/iota/iri/conf/Configuration.java
This PR sets the default alpha value for the random walk to `0.001`,
in order for slower but honest users to still have a good chance of getting their transactions confirmed.
This value is based on both:
1. an analytical calculation of the probability of a transaction with slower PoW time `H ~= 5mins` to still get confirmed (assuming a constant `lambda = 10 TPS` and `H >> h`).
2. validation (of calculation) by running a private testnet (w/ 12TPS spam) where slower transactions were issued and confirmation rates were measured.
Fixes #801 
- Parameter tuning
see Description
=> tip selection: set default alpha value to 0.001

Dockerfile, src/main/java/com/iota/iri/conf/Configuration.java
- Update dockerfile because of outdated Java package referenced
- Fix timestamp to equate snapshot time in UTC
=> Update dockerfile and fix timezone issue

Dockerfile
8u171-1 is not in release anymore and Dockerfile does not build.
Fixes #877 
Bumped JAVA_VERSION to `8u181-1`
=> PPA webupd8team bumped Java to 8u181-1~webupd8~1

src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/tipselection/WalkValidator.java, src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java, src/main/java/com/iota/iri/utils/collections/impl/BoundedSetWrapper.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java, src/test/java/com/iota/iri/utils/collections/impl/BoundedSetWrapperTest.java
If we analyze transactions in `belowMaxDepth` and we pass a certain threshold of transactions we fail.
We also cache the analyzed transactions so that in the future we can quickly fail `belowMaxDepth`.
Fixes #846 
Unit tests were added:
- Long chain tangle
- Test from genesis
- Old snapshot index
- New snapshot index
- Short chain tangle
- Test from genesis
- Old snapshot index
- New snapshot index
1. What should be the threshold values?
MAX_CACHE_SIZE? MAX_ANALYZED_TXS?
2. Write tests for bounded set
3. Run canaries on network
4. Document `belowMaxDepth`
=> Fail early on below max depth - WIP

src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
Removes the bad tips cache. We found that valid txs are being stored there and this disrupts tipselection.
Fixes #900
All unit and regression tests have passed.
=> Remove WalkValidator cache of tips that are below max depth

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/test/java/com/iota/iri/TransactionTestUtils.java, src/test/java/com/iota/iri/TransactionValidatorTest.java
There is a `propagateSolidTransaction` thread that is supposed to cascade solidity from bottom to top.
If a transaction is solid and its approver's other parent is solid then make the approver solid. Then keep on propagating upwards in this manner.
Unfortunately, this didn't happen. The solidified approver didn't reenter the queue so the change was not cascaded.
May help with #899 / #898 
The following unit tests have been added 
- `testTransactionPropagation`
- `testTransactionPropagationFailure`
In addition, canaries were run by @DyrellC and @geminoz.
=> Fix solidity propagation from bottom to top

src/main/java/com/iota/iri/service/API.java
Fix grammar in error messages returned by the API
=> Fix grammar in API responses

src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
Due to recent changes, one no no longer has to mock the `checkSolidity` methods in unit tests.
It is enough to do `updateSolidity()` on a given transaction.
Fixes #846 
All unit tests pass
=> remove checkSolidity mocks

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/controllers/TipsViewModel.java, src/main/java/com/iota/iri/service/TipsSolidifier.java
TipsViewModel is responsible for keeping an accurate picture of the solid and non-solid tips. Currently this view is managed within #TransactionValidator.updateStatus() and a separate TipsSolidifier thread (which is not really efficient since it picks one random non-solid tip at a time each 750ms). This leads to a lag in the tips reality. See also issue #761 and #573. With PR #907 in place, we can manage the TipsViewModel fully within TransactionValidator and keep an accurate and up-to-date picture of the current (solid/non-solid) tips.
=> some TransactionValidator fixes regarding solidity

src/main/java/com/iota/iri/storage/FileExportProvider.java, src/main/java/com/iota/iri/storage/PersistenceProvider.java, src/main/java/com/iota/iri/storage/Tangle.java, src/main/java/com/iota/iri/storage/ZmqPublishProvider.java, src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java, src/test/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProviderTest.java
Currently the java generics used in the `deleteBatch()` method forced us to use non trivial casting.
This change eliminates the use of casting. 
Fixes #939 
All unit tests pass
=> fix generics in RocksDbPersistenceProvider

src/main/java/com/iota/iri/conf/APIConfig.java, src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/test/java/com/iota/iri/conf/ConfigTest.java
The `--remote` flag that opens the api interface to all hosts was accidentally removed. It is now returned
Fixes #952 
Unit tests were added
- `testRemoteFlag()` ascertains that `api_host == 0.0.0.0`
- `testIniParsingTestnet()` now makes sure that `REMOTE` in INI has no effect (This conforms to backwards compatibility)
=> `--remote` flag will enable API interface to all hosts

src/main/java/com/iota/iri/conf/ConfigFactory.java, src/main/java/com/iota/iri/conf/IniDeserializers/CustomBoolDeserializer.java, src/main/java/com/iota/iri/conf/deserializers/CustomBoolDeserializer.java, src/test/java/com/iota/iri/conf/ConfigTest.java
Fixes case insensitive parsing of boolean configurations.
For example `DNS_RESOLUTION_ENABLED = TRUE` failed with the following error:
```
ERROR com.iota.iri.IRI$IRILauncher - There was a problem reading configuration from file: Cannot deserialize value of type `boolean` from String "TRUE": only "true" or "false" recognized
at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.iota.iri.conf.TestnetConfig["DNS_RESOLUTION_ENABLED"])
```
Fixes #724 
Unit tests  were added that ascertain
- Test "TRUE"
- Test "FALSE"
- Test that writing the key with no value gives an error (this is backwards compatible behavior).
- Test that defaults value don't change if keys are missing.
=> Parse case insensitive boolean text

src/main/java/com/iota/iri/network/TCPNeighbor.java
```
@Override
public void send(DatagramPacket packet) {
if (sendQueue.remainingCapacity() == 0) {
sendQueue.poll();
}
byte[] bytes = packet.getData().clone();
sendQueue.add(ByteBuffer.wrap(bytes));
}
```
The sendQueue which is used in #TCPNeighbor.send() is a [ArrayBlockingQueue](https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ArrayBlockingQueue.html) with a capacity of 10. I think this method needs a lock so that the poll() and add() are done synchronized (to prevent queue full exceptions), since three threads are calling this send method:
1. spawnReplyToRequestThread: `replyToRequestFromQueue -> replyToRequest -> sendPacket -> neighbor.send(sendingPacket);`
2. spawnTipRequesterThread:  `neighbors.forEach(n -> n.send(tipRequestingPacket));`
3. spawnBroadcasterThread: …
=> Make TCPNeighbor send() synchronized to prevent queue overflows

checkstyle.xml, pom.xml
The plugin now reads the local checkstyle.xml as default, instead of using the sun_checks.xml on other targets than "mvn validate".
The target "mvn checkstyle:checkstyle" returned more than 5.500 errors reported by checkstyle, because it uses the sun_checks.xml as fallback. I tested the following buid targets and they work correct now:
- mvn validate (worked correct before and after this change)
- mvn checkstyle:check (did not worked before this change)
- mvn checkstyle:checkstyle (did not worked before this change)
Verify the output by running the given maven goals and have a look at the console and the generated xml reports in the target folder.
- [x ] My code follows the style guidelines for this project
=> Optimized maven checkstyle plugin settings

src/main/java/com/iota/iri/service/API.java
Whilest renaming parameters for javadoc purposes, the variable stayed the same.
This happened because map.get just needs an object, so there was no error in the code (so IRI compiled)
Due to this, getBalance was broken. it is now fixed again.
=> renamed addresses to addressList

.travis.yml
Fixes #993 - hard-coded merge to `dev` instead of the upstream branch.
* This merge is needed because Travis does not update PR builds when upstream is changed, and restarting the build does not change the underlying refs.
See related issue
- Personal branch
- This PR itself
- should we also not merge in `push` triggers by wrapping explicit merges w/ `test  $TRAVIS_PULL_REQUEST = "true" && ...`?
=> travis merge to upstream branch

src/main/java/com/iota/iri/IXI.java
When an IXI module fails IRI only shows:
```
09/27 19:16:40.694 [main] ERROR com.iota.iri.IXI - Script error
```
this is not informative enough, and the `scriptEngine` actually gives an informative stack trace, for example:
```
09/27 19:16:40.694 [main] ERROR com.iota.iri.IXI - Script error
javax.script.ScriptException: TypeError: Cannot read property "latestSnapshot" from undefined in <eval> at line number 3
```
- locally while debugging regression on snapshot.ixi
=> IXI add stack trace of scriptEngine eval to help to debug Nashorn scripts

src/main/java/com/iota/iri/network/Node.java
analyzing what happens when a new node tries to sync:
let `N` be the synced node & `n` be the new node.
```
N                      n
<- ?|h(tx)   -      //n requests tx
- tx|h(?)   ->      //N replies with tx
<- tx|h(tx2) -      //n, which just found out about `tx` broadcasts it to every one (and request something else)
```
so in this case `N` will analyze the last packet - i.e. will hash it to check MWM etc.
this is redundant in this case, and is a burdun on `N`.
in my test (8 core) both nodes consumed 400%.
and profiling showed 85% of the CPU is spent in `Curl.transform`
proposed solution:
however, it's simple to see that `n->N tx` can be anticipated, I mean `N` just sent it to `n`.
so y proposal is for `N` to add `tx` to its `recentSeenBytes` list as if it already received it.
this …
=> Caches the reply to request tx to avoid redundant processing

.travis.yml
For some reason, the code coverage tool d/l stopped working.
This fixes the URI query.
Fixes #1082 
- Running Travis CI on my personal repo:
https://travis-ci.org/alon-e/iri/jobs/444323643
https://app.codacy.com/app/alon-e/iri_2/files?bid=7013428
=> fix code coverage tool d/l

.travis.yml, pom.xml
This PR adds jacoco as a java agent and appends to the coverage report from the unit tests.
also, versions are now interpreted semantically by Maven.
- locally running the tests and plotting coverage report to see additional line hits
- on Travis passing tests
- pushing reports to Codacy
=> add code coverage for regression tests

src/main/java/com/iota/iri/BundleValidator.java
Return early when validating a bundle that was already processed.
No functionality was changed.
It is just a quick fix that saves time loading from disk.
All current unit tests have passed
=> Return early when validating a bundle that has a known invalid status

src/main/java/com/iota/iri/Snapshot.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/model/StateDiff.java, src/main/java/com/iota/iri/service/API.java, src/test/java/com/iota/iri/SnapshotTest.java
Various Hashes were created from the wrong hash type, this has been fixed.
Fixes #1079 
Manual verify if all uses of the `HashFactory` and `NULL_HASH`
=> Fixed wrong Hash objects used

python-regression/ciglue.sh
Avoid throwing a fatal error when TIAB has been cloned already.
=> Regression ciglue.sh: avoid git fatal error when cloning TIAB

src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/main/java/com/iota/iri/conf/IotaConfig.java, src/main/java/com/iota/iri/conf/PearlDiverConfig.java, src/main/java/com/iota/iri/service/API.java
Add configuration variable for the number of PoW threads, for manual control.
Fixes #1016 
Deployed to production IOTA node, verified specified number of threads were used by CPU load.
=> Make PearlDiver threads configurable

src/main/java/com/iota/iri/network/Neighbor.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/service/dto/GetNeighborsResponse.java
Seperates "numberOfInvalidTransactions" and "numberOfStaleTransactions" in `getNeighbors`
```
{
"neighbors": [
{
"address": "localhost:12345",
"numberOfAllTransactions": 0,
"numberOfRandomTransactionRequests": 0,
"numberOfNewTransactions": 0,
"numberOfInvalidTransactions": 0,
"numberOfStaleTransactions": 0,
"numberOfSentTransactions": 0,
"connectionType": "tcp"
}
],
"duration": 1
}
```
Fixes #1018 
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_
- Tested locally
=> add "numberOfStaleTransactions" to getNeighbors API call

python-regression/tests/features/machine1/1_api_tests.feature, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
adds  'coordinatorAddress' to 'getNodeInfo' response:
```
curl localhost:14265 \
-X POST \
-H 'Content-Type: application/json' \
-H 'X-IOTA-API-Version: 1' \
-d '{"command": "getNodeInfo"}' | jq
{
"appName": "IRI Testnet",
"appVersion": "1.5.5",
"jreAvailableProcessors": 4,
...
"coordinatorAddress": "HQUUXGMQOVHJFJPOELGYJ9EJYSCLQDGH9F9VYYQAJPR9DRYEYPBFWXTHEVHRMKGHRKJYXIQOLRVOLSXJJ",
"duration": 21
}
```
Fixes #1056 
- locally running a node
- changing Coo address and rerunning tests.
=> add 'coordinatorAddress' to 'getNodeInfo' response.

src/main/java/com/iota/iri/model/persistables/Hashes.java
`Hashes` always contain a set of `TransactionHash`es.
Read() will thus need to make `TransactionHash`. and not the `Hash` of the class type.
ran Unit tests 
=> Changed Hashes generic to always Transaction

src/main/java/com/iota/iri/zmq/MessageQ.java, src/main/java/com/iota/iri/zmq/README.md
Documents zmq/MessageQ
Fixes #1109
=> Document zmq-messageQ

src/main/java/com/iota/iri/BundleValidator.java
Adding documentation to bundle validator
Fixes #1107 
=> Document Bundle Validator

src/main/java/com/iota/iri/TransactionValidator.java
Document `Transaction Validator`
Fixes #1107
=> Transaction Validator Documentation

src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/dto/AbstractResponse.java, src/main/java/com/iota/iri/service/dto/AccessLimitedResponse.java, src/main/java/com/iota/iri/service/dto/AddedNeighborsResponse.java, src/main/java/com/iota/iri/service/dto/AttachToTangleResponse.java, src/main/java/com/iota/iri/service/dto/CheckConsistency.java, src/main/java/com/iota/iri/service/dto/ErrorResponse.java, src/main/java/com/iota/iri/service/dto/ExceptionResponse.java, src/main/java/com/iota/iri/service/dto/FindTransactionsResponse.java, src/main/java/com/iota/iri/service/dto/GetBalancesResponse.java, src/main/java/com/iota/iri/service/dto/GetInclusionStatesResponse.java, src/main/java/com/iota/iri/service/dto/GetNeighborsResponse.java, src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java, src/main/java/com/iota/iri/service/dto/GetTipsResponse.java, src/main/java/com/iota/iri/service/dto/GetTransactionsToApproveResponse.java, src/main/java/com/iota/iri/service/dto/GetTrytesResponse.java, src/main/java/com/iota/iri/service/dto/IXIResponse.java, src/main/java/com/iota/iri/service/dto/RemoveNeighborsResponse.java, src/main/java/com/iota/iri/service/dto/WereAddressesSpentFrom.java
Updated documentation for the DTO classes
Should be merged after #1140, since this is based on that work.
Fixes #1114 
=> Document dto

src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/Iota.java
Includes documentation for the IRI and Iota classes
Fixes #1108
=> Docmented IRI and Iota

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
This PR introduces checks for the config parameters related to Local Snapshots. It simply ensures that the functionality can work as intended by forcing the user to provider parameters that are in the expected range.
=> Introducing a parameter validation for the local snapshot config parameters

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/service/ledger/LedgerService.java, src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java, src/main/java/com/iota/iri/service/milestone/MilestoneService.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneServiceImpl.java
While refactoring the code we introduced a small but severe bug where the generateBalanceDiff method of the LedgerService traversed one milestone too far, booking balances twice.
In addition it fixes the shutdown() order (IRI crashed before - not being able to shutdown all instances in time because some of the legacy shutdown-methods take a really long time to terminate). The shutdown-methods of the new classes terminate instantly.
=> Hotfix for the solidification bug of the Local Snapshots branch

python-regression/tests/features/machine1/1_api_tests.feature
There was an issue with the broadcast regression test. The transaction wasn't given any time to be processed by the sending node's neighbours, causing the transaction to not exist when searched for. This PR adds a delay in `machine1` broadcast regression test so that the transaction has time to be processed and then found on the second node.
The branch was created from the `dev-localsnapshots` branch, and the delay was placed inside. The new branch was then built and tested in buildkite and passed.
=> Regression: Fix Machine 1 Broadcast Test 

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/network/TransactionRequesterWorker.java, src/main/java/com/iota/iri/network/impl/TransactionRequesterWorkerImpl.java
This PR introduces a dedicated background worker that tries to work through the request queue by sending random tips along the requested transactions. This massively increases the sync speed of new nodes that would otherwise be limited to requesting in the same rate as new transactions are received.
Note: To reduce the overhead for the node we only trigger this worker if the request queue gets bigger than the "REQUESTER_THREAD_ACTIVATION_THRESHOLD". Otherwise we rely on the processing of the queue due to normal outgoing traffic like transactions that get relayed by our node.
=> Introducing a dedicated Transaction Requester Background Worker

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
Since the locking of the two Snapshot was intertwined it could happen that we ran into a deadlock situation where the node freezes and doesn't process anything anymore. This PR changes this so the modification of the two snapshots happens without intertwining the locks.
=> Fix: Removed intertwined locks to prevent deadlocks

src/main/java/com/iota/iri/service/ledger/LedgerService.java, src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java, src/main/java/com/iota/iri/service/milestone/LatestSolidMilestoneTracker.java, src/main/java/com/iota/iri/service/milestone/MilestoneService.java, src/main/java/com/iota/iri/service/milestone/impl/LatestSolidMilestoneTrackerImpl.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneServiceImpl.java, src/test/java/com/iota/iri/TangleMockUtils.java, src/test/java/com/iota/iri/service/milestone/impl/MilestoneServiceImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotMockUtils.java
This PR introduces a way to fast forward the ledger state after a restart of IRI. Previously we had to rescan all milestones to rebuild the ledger state. Especially for nodes that start off with a non-snapshotted database, this could take a really long time (a few hours). In combination with the upcoming refactor of the replayMilestones method this allows us to massively decrease the time and resources that are required for this operation (to a few seconds rather than hours).
=> Feat: Added an option to fast forward the ledger state

src/main/java/com/iota/iri/network/TCPNeighbor.java, src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
This PR removes the grace time from the solid entry points generation. It was added in the past to work around the back referencing transaction issue. Since the issue can not be solved by just keeping the solid entry points alive for a little longer time and needs to be addressed separately (we will use cuckoo filters for this later on), it can and should be removed.
Especially in scenarios where we have a lot of TPS and a side tangle (like it happened today) it can slow the snapshot generation noticable and disrupt the operation of the node.
Note: This PR also changes the info message when the sendqueue is full to being a debug message because it can otherwise spam the CLI output making it very hard to debug problems and see important messages of the console output.
- Bug fix (a …
=> Refactor: Removed grace time from solid entry points generation

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
Local snapshot pruning configuration should always be false if Local snapshot is not enabled.
Fixes the problem that getNodeInfo may report that Pruning is enabled while Local Snapshots is disabled.
Existing unit tests have passed
=> Local_Snapshots_Pruning_Enabled should depend on Local_Snapshots_Enabled config

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
This PR changes the boolean flags of local snapshots to accept a value on the command line (true/false).
Before it was only possible to set the value in the config.
=> Refactor: made boolean parameters receive a value

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/network/impl/TransactionRequesterWorkerImpl.java
Because of a bug in the checkSolidity function and a problem with the bottom->top solidifier (missing cuckoo filter) the node started requesting very old transactions and never stopped which at some point overwhelmed the requester (and increased the resource consumption).
=> Fix: Node requested old transactions forever

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/main/java/com/iota/iri/conf/IotaConfig.java, src/main/java/com/iota/iri/conf/SolidificationConfig.java, src/main/java/com/iota/iri/service/Feature.java, src/main/java/com/iota/iri/service/TipsSolidifier.java, src/test/java/com/iota/iri/conf/ConfigTest.java
This PR adds the ability for node owners to disable tip solidification.
The reason behind it is that it potentially takes a lot of resources, so you should be able to disable it.
If it is enabled, it will now show up in the `getNodeInfo['features']` list as "tipSolidification".
Fixes #1242 
- Unit tests
- getNodeInfo, correctly enabled/disabled in features list
=> SolidificationConfig for the tipsolidifier

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
Sets minimum values to pruning delay and depth for local snapshots
Fixes #1217
Unit tests
=> Set minimum values for LS

src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/test/java/com/iota/iri/conf/ConfigTest.java
Change the minimum value for LOCAL_SNAPSHOTS_PRUNING_DELAY to 10,000
Fixes #1265 
Unit tests added to check for failure when we configure value below minimum
=> Change the minimum value for LOCAL_SNAPSHOTS_PRUNING_DELAY

src/main/java/com/iota/iri/model/persistables/SpentAddress.java, src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesProviderImpl.java, src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesServiceImpl.java, src/main/java/com/iota/iri/service/transactionpruning/jobs/MilestonePrunerJob.java
When traversing approved transactions that should be pruned, of we found one that we didn't know about its spending address already, then persist the address and send out a warning.
Also some small refactoring has been made
=> Don't throw on missed spent address. Persist it and warn

src/main/java/com/iota/iri/network/Node.java
The dns refresher does a reverse lookup. If the reverse lookup is successful, neighbors that were added with their IP will be resolved via their DNS name after the lookup. 
By turning off the reverse lookup only neighbors that are added by domain name get periodically checked and updated in the dns resolver thread.
The fix was quite easy by replacing the `getHostName` method that does a reverse lookup with `getHostString` that doesn't do a reverse lookup (see JDK javadocs). This is only a minor change that shouldn't have any side effects.
Fixes # (issue) - no issue submitted
As the dns refresher code is not easily unit-testable, therefore I did an end to end test for UDP neighbors by running a patched node only. There might be a …
=> Fix unwanted dns reverse resolving in dns refresher

src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/main/java/com/iota/iri/conf/SnapshotConfig.java, src/main/java/com/iota/iri/service/snapshot/impl/SnapshotProviderImpl.java, src/main/java/com/iota/iri/service/spentaddresses/SpentAddressesProvider.java, src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesProviderImpl.java
The `SPENT_ADDRESSES_DB` and `SPENT_ADDRESSES_LOG` paths are currently hardcoded. This PR makes them configurable similarly to `DB_PATH` and `DB_LOG_PATH`.
Fix #1268
=> Add configurable variables for spent addresses DB

.travis.yml, pom.xml
reproducible builds:
```bash
dev:
$ mvn clean package
$ sha256sum target/iri-1.5.5.jar 
6b60bbaf34c67e70b6bd7d7ee6ae7a9c1a9fb0f1d4c4d7a7e4293910f5140fd3  target/iri-1.5.5.jar
$ mvn clean package
$ sha256sum target/iri-1.5.5.jar 
e49e47850371c937cc8fda78392a8c2a2fb13c69540ffe2994ac71abe34d64c1  target/iri-1.5.5.jar
----
after fix:
$ mvn clean package
$ sha256sum target/iri-1.5.5.jar 
06f7f2c4714d45de710a67670b59bfbe6202ad54c77663518e221662cc887ab2  target/iri-1.5.5.jar
$ mvn clean package
$ sha256sum target/iri-1.5.5.jar 
06f7f2c4714d45de710a67670b59bfbe6202ad54c77663518e221662cc887ab2  target/iri-1.5.5.jar
```
Fixes #1193
- see description
=> add a plugin to create reproducible builds.

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotProviderImpl.java
In #1274 the `assertSpentAddressesDbExist()` method was changed incorrectly.
Now it is fixed to assert the content of the correct directory.
Ran in debug mode and tested
=> Fix: test existence of spent addresses db do not point to correct folder

src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java
To prevent jumping back and forth in and out of sync, there is now a buffer in between.
Only when the latest milestone and latest snapshot differ more than this number, we fall out of sync
Fixes #1209
Not yet tested, will request a node as soon as possible.
submitting the PR to start possible discussion about the implementation
=> Fix: added a buffer to LSManager

src/main/java/com/iota/iri/service/API.java
_Please include a summary of the change. Include the motivation for the change._
https://github.com/iotaledger/iri/issues/1086
Made CORS requests and it now works on blink engine browsers (Firefox, safari etc)
=> Fix for (closed) issue #1086, missing user-agent header in cors

src/main/java/com/iota/iri/network/TransactionRequester.java, src/test/java/com/iota/iri/controllers/TransactionRequesterTest.java, src/test/java/com/iota/iri/network/TransactionRequesterTest.java
Keep the `transactionToRequest` Set of the `TransactionRequester` fresh with new inbound transactions instead of keeping stale ones when at capacity.
Fixes #1313 
- Unsynced node that lag greatly behind seem to sync faster since we do not pile up stale transations anymore.
=> Fresh transactionToRequest

src/main/java/com/iota/iri/BundleValidator.java, src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/ledger/LedgerService.java, src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneServiceImpl.java, src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java, src/main/java/com/iota/iri/service/spentaddresses/SpentAddressesService.java, src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesServiceImpl.java, src/main/java/com/iota/iri/utils/IotaUtils.java, src/test/java/com/iota/iri/TangleMockUtils.java, src/test/java/com/iota/iri/TransactionTestUtils.java, src/test/java/com/iota/iri/TransactionValidatorTest.java, src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java, src/test/java/com/iota/iri/service/ledger/impl/LedgerServiceImplTest.java, src/test/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesProviderImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/CumulativeWeightCalculatorTest.java, src/test/java/com/iota/iri/service/tipselection/impl/RatingOneTest.java, src/test/java/com/iota/iri/service/tipselection/impl/TailFinderImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkerAlphaTest.java
1. While we are applying a milestone, persist validated spent addresses in the db from confirmed transactions.
2. Stop persisting them while taking a local snapshot
3. Adds unit tests while doing neccessary refactoring to make the code more testable
Fixes #1321
Unit test added
Canary have been ran on the mainnet
=> Fix: Reduce db access and cpu usage needed to persist spent addresses

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/service/transactionpruning/TransactionPruner.java, src/main/java/com/iota/iri/service/transactionpruning/async/AsyncTransactionPruner.java, src/main/java/com/iota/iri/service/transactionpruning/async/MilestonePrunerJobQueue.java, src/main/java/com/iota/iri/service/transactionpruning/async/SimpleJobQueue.java, src/main/java/com/iota/iri/service/transactionpruning/jobs/MilestonePrunerJob.java
Don't persist the pruner state. In case of a restart there will be transactions that won't be pruned.
Fixes #1340
Node will be ran with this code. Results will be posted in comments.
=> Change: Do not persist pruner state

src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesProviderImpl.java, src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java
1. Ensures that in general RocksDb will go through its internal bloom filter when checking for existence
2. Make the `WereAddressesSpentFromProvider` use the rocksDB `exists`
Relates to #1291
Unit tests will be written in #1091 and when we refactor the db
=> Fix: Db exists() method optimization

README.md
Changes to the readme to point to the correct documentation. Readme.io was deprecated and the links did not work anymore. 
=> readme links fix

src/main/java/com/iota/iri/IXI.java, src/test/java/com/iota/iri/IXITest.java
Calling an unknown command of a known IXI returns `{"duration":0}`. This change will return the standard error message `Command [Foo.bar] is unknown`.
=> Fix unknown IXI command response

.travis.yml, DOCKER.md, pom.xml, src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/utils/IotaUtils.java
1. One source of truth for version in POM
1. Changes local `mvn clean package` runs to output jar versions in the form `X.X.X-DEV-{git_hash_abbrev}.
2. Official builts by the CI will have another version.
3. The version is now also added to the jar manifest.
4. When running from IDE version is parsed exactly as it is in POM
Fixes #1220
1. maven was ran locally
2. IRI was run locally
2. Travis passed
=> Prepare IRI to have its version injected by CI

src/main/java/com/iota/iri/utils/BitSetUtils.java, src/main/java/com/iota/iri/utils/datastructure/CuckooFilter.java, src/main/java/com/iota/iri/utils/datastructure/impl/CuckooFilterImpl.java, src/test/java/com/iota/iri/utils/datastructure/impl/CuckooFilterImplTest.java
This PR introduces a Cuckoo Filter that is going to be used in connection with local snapshots to overcome the problem of back referencing transactions (see the connected issue). It is is a probabilistic data structure that supports fast set membership testing. It is very similar to a bloom filter in that they both are very fast and space efficient. Both the bloom filter and cuckoo filter also report false positives on set membership.
Cuckoo filters are a relatively new data structure, described in a paper in 2014 by Fan, Andersen, Kaminsky, and Mitzenmacher (https://www.cs.cmu.edu/~dga/papers/cuckoo-conext2014.pdf). They improve upon the design of the bloom filter by offering deletion, limited counting, and a bounded false positive probability, while still maintaining a similar space …
=> Introducing a Cuckoo Filter for local snapshots

Dockerfile
For each "FROM" directive in the Dockerfile I added the respective sha256 container hash as stored in docker hub. This adds a layer of security making sure that the Dockerfile, as cloned from the official IRI repo, builds only if the sha256 digests match.
=> Dockerfile: added docker FROM containers sha256 digests

src/main/java/com/iota/iri/TransactionValidator.java
This change will make IRI request bigger portions of Tangle while exploring transactions for solidity.
Fixes #1310 
=> Change: Do not request one transaction at a time when checking for solidity

src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/service/dto/GetNeighborsResponse.java, src/test/java/com/iota/iri/network/NodeTest.java, src/test/java/com/iota/iri/service/dto/GetNeighborsResponseTest.java
Will return the ip address on api call to getNeighbors.
Fixes #1276 
- Created unit tests in GetNeighborsResponseTest
- Start iri with <code>--testnet -n tcp://1.2.3.4:15600</code>
- <code>curl http://localhost:14265 -X POST -H 'Content-Type: application/json' -H 'X-IOTA-API-Version: 1' -d '{"command": "getNeighbors"}'</code>
=> Fix #1276: Return ip address instead of hostname in getNeighbors

python-regression/ciglue.sh
Enable support for local IXI modules uploading in regression tests by passing `create_cluster.py` the path to base `python-regression` folder.
=> ciglue.sh IXIs path relative to python-regression base folder

src/main/java/com/iota/iri/conf/ProtocolConfig.java, src/main/java/com/iota/iri/service/snapshot/SnapshotService.java, src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java, src/main/java/com/iota/iri/service/snapshot/impl/SnapshotProviderImpl.java, src/main/java/com/iota/iri/service/snapshot/impl/SnapshotStateImpl.java, src/test/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotMetaDataImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotMockUtils.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotProviderImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotStateDiffImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotStateImplTest.java
Added unit tests to all other local snapshot files
Added javadoc to LS related config
Fixes #1091 
Cannot be merged before merging of #1363
=> Test: Local Snapshot unit tests

src/main/java/com/iota/iri/network/Node.java
Recent seen transactions cache must only hash transaction trytes instead of the whole network packet.
Fixes #1452
Bug fix (a non-breaking change which fixes an issue)
=> Fix: recent seen transactions digest

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
While traversing the transactions approvers we use the arrival time of the original root transaction instead of the `currentTransaction`.
A unit test needs to be added
=> Fix: fetch correct arrival time while traversing dags for orphaned transactions.

.gitignore
The spent-address-db and log are now added to `.gitignore`, so that we wont commit them accidentally
Fixes #1440
Git doesnt add folders to changes in current dir anymore
- [] I have added tests that prove my fix is effective or that my feature works
=> Feature: Added spent-address db folders to gitignore

pom.xml, src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/model/persistables/Transaction.java, src/main/java/com/iota/iri/service/API.java, src/test/java/com/iota/iri/network/NodeTest.java, src/test/java/com/iota/iri/service/APIIntegrationTests.java, src/test/java/com/iota/iri/service/APITest.java, src/test/java/com/iota/iri/service/NodeIntegrationTests.java, src/test/java/com/iota/iri/service/ledger/impl/LedgerServiceImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkerAlphaTest.java
In API method storeTransactionStatement arrival date was set in seconds. Changed that to milliseconds. See cliri bug fix referenced in issue.
Fixes #766 
Replaces PR #1369
* Added tests
* Updated mockito (for new tests)
* Refactored incompatible mockito usage
* Made Iota.configuration private (instance access not needed and should be injected. Was easier to use this way in tests, too)
* Added documentation that arrival time is in millis
Attention: SnapshotServiceImpl#isOrphaned NOT changed. See comment in issue.
Unit tests that check that set arrival time is close to System.currentTimeMillis
=> Fix: set arrival time in millis (not seconds) (#766)

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
Disables the tip solidifier in order to reduce syncing overhead.
The suggestion is that the milestone solidifier is enough to have a healthy tangle
Tests on the ICC network concluded that this is safe
=> Disable Tip Solidifier

.travis.yml, pom.xml
Removes the maven commit plugin.
Also make sure Travis won't use it.
Get rid of ` Welcome to IRI 1.7.1-DEV-${git.commit.id.abbrev}` annoying log message
Fixes #1415 
If the PR passed the CI it will be enough
=> Remove git-commit plugin

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java
Changes the `TransactionValidator`'s `checkSolidity()` method to use a `LinkedHashSet` in order to keep the order in which transactions got analyzed. The `TransactionViewModel`'s`updateSolidTransactions()`  method will then update the solid flag of the given txs in reverse order to guarantee that the flags are updated from past to present. 
refs: https://github.com/iotaledger/iri/pull/1491
#1187 (maybe)
#1292 (maybe)
Private Net.
=> Fix: Update solidity of transactions from past to present in TransactionValidator

python-regression/tests/features/machine6/config.yml
After the inclusion of https://github.com/iotaledger/iri/pull/1471 into `dev` the pruning logic defaults to `false`, this adds the `true`
Fixes #1289 
Ran test locally to see if the pruning was enabled on the nodes for `machine6` after pulling #1289 into my local branch.
=> Regression: Fix snapshot pruning config for machine6

src/main/java/com/iota/iri/service/spentaddresses/SpentAddressesProvider.java, src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesProviderImpl.java
adds a getAll() method to get all spent addresses known to the node
Required for #1450
Replaces #1490
Tested by @kwek20 in the previous PR
=> Feature: Add getAllAddresses to the spentAdddresses provider

src/main/java/com/iota/iri/network/NeighborRouter.java
If we initialize a connection to a neighbor ourselves, we should not remove that URI from the reconnect
pool up on the initialized (but not handshaked) connection, because it will lead to the node
not retrying a reconnect attempt in case the handshaking/read op. was faulty.
=> Fix: prevent self initialized connection being removed from reconnect pool too early

.gitignore
Updated gitignore to include eclipse checkstyle and benchmark folders
=> Fix: Update .gitignore

pom.xml
Even though we are using Jackson only to parse configurations, we want the latest security fixes
Configuration unit tests pass
=> Fix: Up jackson-databind version to 2.9.9.1

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/network/TransactionRequester.java
Fixes transactions to be deemed invalid by their timestamp because the bypass via the `transactionRequester.isTransactionRequested()` doesn't work with the new request queue logic via https://github.com/iotaledger/iri/pull/1530
https://github.com/iotaledger/iri/issues/1541
=> Fix: Adds recently requested txs set to TransactionRequester

pom.xml, src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/service/snapshot/impl/SnapshotProviderImpl.java, src/main/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesProviderImpl.java, src/test/java/com/iota/iri/service/spentaddresses/impl/SpentAddressesProviderImplTest.java
We now check the existence of spent-addresses by properly reading from the db rather then looking for sst files. We do it when we load from local snapshot and when we are not it testnet mode.
Fixes #1461
- Tested manually on a local node
- Unit test was added
=> Fix: Read from the db in order to find the existence of spent-addresses

pom.xml
Stop using shade plugin and create only one jar with all dependecies
Fixes #1189 
`mvn clean package` built jar locally
Also obviously if automation passes all is fine
=> Use maven assembly plugin to create one jar with all dependencies

.travis.yml
Travis fails to pass with oracleJDK 8. 
In this PR we will try to make it pass or stop using jdk8 all together.
Travis is still needed until we add a few more features to buildkite
We see if Travis passes
=> Build: attempt to fix oracle jdk build with travis

checkstyle.xml, src/main/java/com/iota/iri/service/dto/AbstractResponse.java, src/main/java/com/iota/iri/utils/thread/BoundedScheduledExecutorService.java
adds checkstyle rules to enforce:
1. Inner classes are always in the end
2. public constants are always UPPER_SNAKE_CASE
```
<module name="ConstantName">
<property name="applyToPrivate" value="false"/>
<property name="applyToProtected" value="false"/>
<property name="format"
value="^log(ger)?$|^[A-Z][A-Z0-9]*(_[A-Z0-9]+)*$"/>
</module>
<module name="InnerTypeLast"/>
``` 
See #642 
- style fix
Only a style change. Automatic tests suffice.
=> Checkstyle: add inner type and constants rules

src/main/java/com/iota/iri/service/ledger/impl/LedgerServiceImpl.java
Through a redundant break statement, the balance diff creating method did return before it actually computed any balance diff, leading to every applied milestone to not change any addresses.
Weird is that no unit or regression tests catched this. We should have a regression test which mutates addresses and then does a `getBalances()` call to check that the address really was mutated (I didn't check whether we already have such regression test).
Applied this patch to my localsnapshot/spent-addresses RocksDB PR and verified that the mutated balances were not zero anymore.
=> Fix: Fixes regression introduced through the bundle validator refactor

src/main/java/com/iota/iri/network/NeighborRouter.java, src/main/java/com/iota/iri/network/neighbor/Neighbor.java, src/main/java/com/iota/iri/service/dto/GetNeighborsResponse.java
This PR alters the logic of neighbor properties and the `getNeighbors()` API call to fulfill following rules:
* if the neighbor is connected and there's no mapping to a domain, the IP address will be set in the `domain` field
* if the neighbor is connected and there's a mapping to a domain, the domain will be set in the `domain` field
* if the neighbor is not connected, the neighbor was added using an URI with a domain (tcp://example.com:15600) and during the call to `getNeighbors()` the domain can't be resolved to an IP address, the `domain` field will contain the domain name and the `address` field will be empty
* if the neighbor is not connected, the neighbor was added using an URI with an IP address (tcp://1.1.1.1:15600), the `domain` field will contain the IP address and the …
=> Fix: Always set the domain field of a neighbor

src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/test/java/com/iota/iri/service/tipselection/impl/TipSelectorImplTest.java
Replaces #1612
In #1596 we introduced a bug. If one calls GTTA with the reference parameter, and no CW map was created, then we get an `InvalidAlgorithmParaemterException` since IRI assumes that we chose to promote a transaction that is not in the cone of our entrypoint milestone.
To fix this bug we do full validation on the `reference` transaction:
- It exists
- It is solid
- It is a tail (I don't think it was a requirement before, but as far as I am aware we should only promote tails)
- It is not below max depth
- It is consistent with our first tip.
Unit tests added.
GTTA call with reference was successful when alpha == 0
Regression test needs to be added still once PYOTA is ready.
=> Fix: Ensure reference transaction is valid when alpha is 0

python-regression/tests/features/machine1/1_api_tests.feature, python-regression/tests/features/machine1/config.yml, python-regression/tests/features/machine2/2_transaction_tests.feature, python-regression/tests/features/machine2/config.yml, python-regression/tests/features/machine3/3_blowball_tests.feature, python-regression/tests/features/machine3/config.yml, python-regression/tests/features/machine4/4_stitching.feature, python-regression/tests/features/machine4/config.yml, python-regression/tests/features/machine5/5_milestone_validation.feature, python-regression/tests/features/machine5/config.yml, python-regression/tests/features/machine6/6_local_snapshots_tests.feature, python-regression/tests/features/machine6/config.yml, python-regression/tests/features/steps/response_handling_steps.py
Simple update to node labels in regression tests for log artefact creation during buildkite testing. This will allow for easier debugging of tests in the future. This also includes a reduction in the machine6 wait times. 
-Update to regression files 
Purely syntax changes
=> Update regression node names, m6 times

python-regression/tests/features/machine3/config.yml
Update the regression test `machine3` checksum. A new db has been uploaded for the test and the checksum needs to be updated to allow tests to pass.  
-Local checksum matches downloaded DB checksum for `machine3` tests
=> Update machine3 checksum

python-regression/tests/features/machine3/config.yml, src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkerAlpha.java
Under the right spam conditions nodes have a tendency to spit out chains of transactions rather than a dag. The reason for this is that the alpha == 0 implementation does not filter out transactions added after the walk has started, and so, in higher tps environments, the spam will begin creating a chain of transactions due to the synchronised nature of the calls. This rating filter allows the DAG to spread out more evenly.
-Tested on ICC network as well as in private networks set up locally. 4 nodes with GTTA spammers on each, and the spaghettification is mitigated significantly in higher TPS environments.
=> RatingOne filter for alpha == 0

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
Changes the `α` value to zero and thus lets the node skip cumulative weight calculation during tip-selection.
Running existing unit tests.
=> Feature: Set alpha to zero

src/test/java/com/iota/iri/service/tipselection/impl/TipSelectorImplTest.java
Since we changed default alpha to 0, the tipselImpltest behaves different.
Adding the value a>0 fixes this issue.
This was not seen before since the tests were made separate of the alpha change
Unit tests pass, node runs tipsel properly under 10 TPS load
=> Added non-0 zero alpha to test configuration

src/main/java/com/iota/iri/MainInjectionConfiguration.java, src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/main/java/com/iota/iri/conf/SolidificationConfig.java, src/main/java/com/iota/iri/service/milestone/impl/LatestSolidMilestoneTrackerImpl.java
Adds an option to disable the printing of progress information to the console about synchronization. This is useful for Dyrell who's spamming milestones in a fast fashion, where however the printing of the progress bar slows down that process too much for generating DBs.
=> Adds config option to disable sync progress printing

src/main/java/com/iota/iri/model/persistables/Transaction.java, src/main/java/com/iota/iri/network/pipeline/PreProcessStage.java, src/main/java/com/iota/iri/network/protocol/Protocol.java, src/main/java/com/iota/iri/network/protocol/ProtocolMessage.java, src/main/java/com/iota/iri/utils/TransactionTruncator.java, src/test/java/com/iota/iri/TransactionTestUtils.java, src/test/java/com/iota/iri/network/SampleTransaction.java, src/test/java/com/iota/iri/network/protocol/ProtocolTest.java, src/test/java/com/iota/iri/utils/TransactionTruncatorTest.java, src/test/java/com/iota/iri/utils/dag/DAGHelperTest.java
Lets the `Transaction` `Persistable` truncate the transaction bytes up on saving it by removing zero bytes from the signature message fragment (from the right). Up on loading a transaction, the bytes are back expanded to their full capacity (1604 bytes). This reduces the stored size of a transaction up to 81% (given a complete empty signature message fragment).
https://github.com/iotaledger/iri/issues/1626
Moved the expand/truncate methods from the `Protocol` class to a new separate class called `TransactionTruncator` and writing relevant unit tests for it.
=> Feature: Truncate transaction bytes before persisting them to the database

src/main/java/com/iota/iri/model/StateDiff.java
Performance optimization of `StateDiff#bytes` to only use 1 new byte array instead of `stateMap.size * 2` arrays.
Fixes #603 
=> Memory optimization of StateDiff.bytes() to only use 1 new byte array instead of stateMap.size * 2 arrays

src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java, src/main/java/com/iota/iri/utils/IotaIOUtils.java
Copy/pasting the OPTIONS file in rocksdb in place of the config file we use should work.
However previously, sections were not supported, resulting in `null` and default options beeing loaded.
This adds the ability to load from both a partial or a full OPTIONS file
Fixes #1624
Loaded both a OPTIONS file from another location, and a small config file
=> Fix: Updated db config loading to account for sections

CONTRIBUTING.md
Adds regression tests reference
Fixes #1284 
=> Documentation: Update CONTRIBUTING.MD

src/main/java/com/iota/iri/zmq/README.md
Delete non existing zmq configurations.
Fixes #1597 
=> Fix: Zmq documentation

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java
While rescanning the DB we are not suppose to re-save the existing transactions themselves.
Unfortunately it seems like we were re-saving the transactions and dropping the `TAG` data itself.
Currently I am rescanning a node. I will validate that Tag information is present before merging.
Complete regression test should be done seperatly in #1466
=> Fix: Don't resave the transaction itself

src/test/java/com/iota/iri/benchmarks/BenchmarkRunner.java
We have added the following flags to benchmark runner:
`-Dforks` - How may time should the jvm fork. Running more than one fork will cause more iterations but should reset JVM optimization profiles. May reduce variance. Default Value: 1.
`-DwarmUpIterations` - How many warm up iterations we should run before we stop measuring. Default value: 5
`-DmeasurementIterations` - How many measurement iterations we should have. Default value: 10
`-Dthreads` - How many threads will run the test (concurrency). Default value: # of cores.
Example of how to run from CLI:
`mvn -Dtest=BenchmarkRunner#launchDbBenchmarks -Dforks=2 -DmeasurementIterations=6 -DwarmUpIterations=2 -Dthreads=3 test`
Fixes #1651 
- Test Enhancement (a non-breaking change which adds functionality)
Locally run the example line. The …
=> Allow to configure benchmark from CLI

src/main/java/com/iota/iri/service/tipselection/impl/WalkerAlpha.java
Currently the walker uses an `if(!Collections.EMPTY_MAP.equals(ratings))` check to determine if the alpha value is 0 in the walker. But since the ratings list is is provided by `ratingOne` this list is not empty. Therefore the node is still performing the walk as though the alpha is not 0. The improved behaviour from not doing the ratings calculation has been the result of the alpha 0 change, but having the walk skip the additional unnecessary calculations on the walk end should show another improvement to response time. 
-Set a break point in the walker to make sure that the walk is registering the correct alpha value and using the correct logic
=> Fix: Correct walker behaviour for alpha == 0

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
Enforces the following definition for a solid entry point:
> A transaction is considered a solid entry point if it is a bundle tail that can be traversed down from a non-orphaned transaction that was approved by a milestone that is above the last local snapshot. Or if it is a bundle tail of a non-orphaned transaction that was approved by a milestone that is above the last local snapshot. 
Before non-tails could have been solid entry point, this caused problems in the case they were common to different bundles.
- My node was able to sync with the LS created.
- Using https://github.com/iotaledger/Snapshot.ixi I compared the ledger state of a node that is synced from last global snapshot to my synced node.
=> Fix: Ensure proper creation of solid entrypoints

src/main/java/com/iota/iri/network/NeighborRouterImpl.java, src/main/java/com/iota/iri/service/API.java
If the node has attempted to add a neighbour whether successfully or not, then removing the neighbour should return 'ok'.
Fixes #1586 
- Unit tests pass
=> Remove neighbours

python-regression/util/test_logic/api_test_logic.py, src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java
Fix failed regression tests after caching `TransactionViewModels`.
I realized that when running `BundleValidator#loadTransactionsFromTangle` for a given tx, it could happen that the `tx.branch` or `tx.trunk` could be older than what's in the cache. So we read from cache always.
Secondly, fresh tx i.e `parsed=false` were being gossiped to the node and `tx.store` was overriding the already parsed tx in the cache. So some sort of `cache.putIfAbsent` was necessary for `tx.store`.
Only way cached tx update is by `tx.update`
=> Fix regression tests for cached Transactions

python-regression/tests/features/steps/api_test_steps.py, python-regression/util/neighbor_logic/neighbor_logic.py, python-regression/util/test_logic/value_fetch_logic.py
Fix regression tests that are now running on Python3.
By running our BuildKite pipelines.
https://buildkite.com/iota-foundation/iri-regression-tests/builds/1323
=> Regression tests to python3

src/main/java/com/iota/iri/network/NeighborRouterImpl.java
While regression tests run, it is possible that the nodes will fail to connect to one another at some point if the kubernetes node has not been loaded all the way yet. During the fetch logs portion of the pipeline, it will scan the logs for errors, and if there is a faulty neighbor connection, it will fail the tests regardless of if they've passed prior to this point. By lowering the error message to a warning rather than an error, it will not fail passed tests on log fetching anymore. 
Fixes # The consistently failing regression tests in buildkite
=> Lower error severity for faulty neighbor 

src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/test/java/com/iota/iri/cache/CacheTest.java
Added null check before cache put. Fixes 
```
01/26 20:54:46.064 [Milestone Solidifier] ERROR MilestoneSolidifier:465 - Error while solidifying milestone #1071451
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011) ~[na:1.8.0_181]
at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006) ~[na:1.8.0_181]
at com.iota.iri.cache.impl.CacheImpl.put(CacheImpl.java:107) ~[iri-PR-e1526d2-e8e23c4c.jar:PR-e1526d2-e8e23c4c]
at com.iota.iri.cache.impl.CacheImpl.get(CacheImpl.java:78) ~[iri-PR-e1526d2-e8e23c4c.jar:PR-e1526d2-e8e23c4c]
at com.iota.iri.controllers.TransactionViewModel.fromHash(TransactionViewModel.java:158) ~[iri-PR-e1526d2-e8e23c4c.jar:PR-e1526d2-e8e23c4c]
at …
```
=> check for null key and value before cache.put

python-regression/tests/features/steps/response_handling_steps.py, python-regression/tests/features/steps/transaction_steps.py
A fix for transaction issuance referencing another transaction in the regression tests. The machine 4 tests are reliant on this and have been exhibiting failures using the pool logic. This replaces the pool logic with simple synchronous api calls to ensure the test follows through properly. 
- Ran tests locally for machine 4 tests
=> Fix reference transaction logic

src/main/java/com/iota/iri/controllers/ApproveeViewModel.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java
During creation of TVM's the `TransactionViewModel.fromHash()` function will try to fetch the object from the cache first. If the object doesn't exist in the cache it will then try to fetch it from the db. If it doesn't exist in the db a new transaction is formed for the TVM, and then subsequently placed in the cache. This can happen in several places but there is a compounding effect during syncing as a transaction may be stored, but the trunk and branch of that transaction are not. Each time a `fromHash()` is called on those objects they are found in the cache as empty objects. So long as the empty object is found in the cache, new transactions will not be allowed to be stored until the empty object has been released. This cascades over into the `ApproveeViewModel` as well by filling …
=> Cache: Check for empty entries before adding them to cache

src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/main/java/com/iota/iri/controllers/ApproveeViewModel.java, src/main/java/com/iota/iri/controllers/MilestoneViewModel.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/storage/Tangle.java, src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java, src/test/java/com/iota/iri/service/milestone/impl/MilestoneServiceImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImplTest.java
Fixes the following
- A tx could be cached and updated but not saved to DB during `cacheRelease` that was only called during tangle shutdown
- Move release code from the cache to VMs. Ensures that txs are saved to DB before releasing.
- Ensure to release all `releaseCount` txs from the cache
- Release all txs from cache during tangle shutdown.
- `dirty` tx kept saving to DB (increasing size) because it was still dirty even after being brought back to live from weakstore after release.
=> fix issue where updated tx was not saved to DB

src/main/java/com/iota/iri/network/pipeline/ReplyStage.java
There has been a syncing issue that arose from the internal tests that resulted in a flood of back and forth gossiping of the latest milestone. It fills the queues and stops the node from processing relevant transactions in a timely manner. This issue self corrects at times, but in other cases it stalls out for hours. It is possible that this is caused by the continued pushing of these transactions to the neighbors through the reply stage. 
- After running a node with this change I did not experience the sync issue
=> Remove ping pong from reply stage

src/main/java/com/iota/iri/controllers/AddressViewModel.java, src/main/java/com/iota/iri/service/milestone/impl/LatestMilestoneTrackerImpl.java
This reverts commit b658b8857ed9fdf5736c124e148d4e1e0037e6e6.
In DB's with large collections of milestones, the `LatestMilestoneTracker` gets stalled out in the collection phase as it tries to create and sort all the milestone transaction objects. This can also cause memory errors in large enough db's and can stall out the milestone tracking process.
- Started node with 1M+ milestones and it did not stall on milestone tracking
=> Revert milestone sorting

src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java, src/main/java/com/iota/iri/service/transactionpruning/TransactionPruner.java, src/main/java/com/iota/iri/service/transactionpruning/async/AsyncTransactionPruner.java
In order to prevent pruning logs for the same milestones, we wait for the current job to finish
This is done by checking the jobqueue for any active or pending jobs.
Only one times pruning message is logged
=> Change: Added check for jobs in the transaction pruner

src/main/java/com/iota/iri/conf/SnapshotConfig.java
`LOCAL_SNAPSHOTS_DB_MAX_SIZE` could be set to -1, but its behaviour was undefined.
Now we clearly say that it means that the database size does not affect anything when set to -1
=> Config: Db maximum size explanation

src/main/java/com/iota/iri/cache/impl/CacheManagerImpl.java, src/main/java/com/iota/iri/conf/BaseIotaConfig.java, src/main/java/com/iota/iri/conf/DbConfig.java, src/test/java/com/iota/iri/conf/ConfigTest.java
The configuration for Milestone cache size was erroneously called `MILESTONE_BATCH_WRITE`
Now it is called `MILESTONE_CACHE_SIZE`
`ConfigTest#testIniParsingMainnet()` has been amended to check that INI parsing will work for this config.
=> Fix: Change INI config to be called MILESTONE_CACHE_SIZE

src/main/java/com/iota/iri/network/NeighborRouterImpl.java
Adds port number validation to neighbour URI.
The port number is an unsigned 16-bit integer, so max is 65535. See [port](https://en.wikipedia.org/wiki/Port_(computer_networking))
Fixes #1678 
=> validate port number on addNeighbor API

src/main/java/com/iota/iri/service/API.java, src/test/java/com/iota/iri/service/APIIntegrationTests.java
Removes the unused `threshold` parameter from `getBalances` API call.
Fixes #1723 
- Manually called `getBalances` on a node with and without threshold.
=> Remove threshold from getbalances API call

src/main/java/com/iota/iri/service/API.java
If the tvm for a  hash supplied during `getTrytes` api call is null, put null in the response instead of returning a shorter list.
Fixes #965
Unit tests pass
=> getTrytes API: add null to response list of tvm is null

src/main/java/com/iota/iri/utils/IotaUtils.java, src/test/java/com/iota/iri/utils/IotaUtilsTest.java
Default value for size should be gb, but it was in upper case. 
=> Fix: made gb default lowercase

src/main/java/com/iota/iri/controllers/TransactionViewModel.java
When a node sees a transaction it may have seen before it won't insert it into the cache to not override the existing transaction.
Fixes a problem where we may be switching instances of txs and thus not setting them solid, because we skip the `updateStatus` method
TBD
=> Only cache after exists check passes

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/MainInjectionConfiguration.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/network/NetworkInjectionConfiguration.java, src/main/java/com/iota/iri/network/pipeline/ReceivedStage.java, src/main/java/com/iota/iri/network/pipeline/TransactionProcessingPipelineImpl.java, src/main/java/com/iota/iri/network/pipeline/ValidationStage.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java, src/main/java/com/iota/iri/service/validation/TransactionValidator.java, src/test/java/com/iota/iri/MainInjectionConfigurationTest.java, src/test/java/com/iota/iri/network/NetworkInjectionConfigurationTest.java, src/test/java/com/iota/iri/network/pipeline/ReceivedStageTest.java, src/test/java/com/iota/iri/network/pipeline/TransactionProcessingPipelineTest.java, src/test/java/com/iota/iri/network/pipeline/ValidationStageTest.java, src/test/java/com/iota/iri/service/APITest.java, src/test/java/com/iota/iri/service/validation/TransactionValidatorTest.java
Part of the #1646 breakdown. To prepare for the migration of solidity logic from the `TransactionValidator`, we will be moving the `TransactionValidator` to a more appropriate location. As it is a service, it will now be located in the service directory under the validation sub-directory.
- Regression and Unit tests continue to pass
=> Move validation to validation service package

src/main/java/com/iota/iri/MainInjectionConfiguration.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/milestone/MilestoneSolidifier.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java, src/main/java/com/iota/iri/service/tipselection/TipSelSolidifier.java, src/main/java/com/iota/iri/service/tipselection/impl/AsyncTipSelSolidifier.java, src/main/java/com/iota/iri/service/tipselection/impl/DummyTipSelSolidifier.java, src/main/java/com/iota/iri/service/tipselection/impl/FakeTipSelSolidifier.java, src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java, src/test/java/com/iota/iri/service/APITest.java, src/test/java/com/iota/iri/service/ApiCallTest.java, src/test/java/com/iota/iri/service/tipselection/impl/TipSelectorImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
While doing GTTA we will attempt to solidify transactions we walk across.
This will make sure that transactions that we missed out on for whatever reason will solidify
Fixes #1818
I ran both 1.8.5 and a canary with this change.
I called GTTA in a loop on both with JMETER
GTTA with this change was still faster compared to 1.8.5.
Throughput: 176.662 ops/minute compared to 71.603 ops/minute
However, profiling showed that solidifying takes 30 % of cpu time...
=> Solidify transactions we walk across while doing GTTA

src/main/java/com/iota/iri/network/pipeline/BroadcastStage.java, src/main/java/com/iota/iri/network/pipeline/SolidifyStage.java, src/main/java/com/iota/iri/network/pipeline/TransactionProcessingPipelineImpl.java, src/test/java/com/iota/iri/network/pipeline/BroadcastStageTest.java
When the transaction solidifier was introduced, we updated how transactions are passed through to broadcast, and under initial review we opted to fetch broadcast transactions at the end of the solidification stage, to pass them forward to the broadcast stage in the event the original solidifying transaction is not solid. This sequential loading of transactions from the broadcast queue does not forward transactions fast enough. To correct this, the logic has been moved to the broadcast stage instead. The broadcast stage will complete the transaction forwarding as it was previously designed to do, and the broadcast stage will check if a transaction still exists to broadcast, and if there is, it will pass it to the broadcast stage queue until there is nothing left to pull out of the set. …
=> Update Broadcast Stage logic 

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/network/pipeline/ReceivedStage.java, src/main/java/com/iota/iri/service/API.java, src/test/java/com/iota/iri/TransactionValidatorTest.java, src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java, src/test/java/com/iota/iri/network/pipeline/ReceivedStageTest.java, src/test/java/com/iota/iri/service/APITest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
Txs that were being quick set solid were not being persisted upon release from cache.
This change ensures that updates are always persisted by assuming responsibility to always call `tvm.update`
Also, fixes is a possible race condition with `tvm.shouldPersist` and cache metric fields.
- Existing and new unit tests that assert persistence pass.
- Buildkite will run reg tests :)
=> Fix visibility problem on shouldPersist and refactor tvm update methods

.vscode/settings.json, src/main/java/com/iota/iri/service/API.java
As compass is using depth 1, we force our gtta to always be depth 0
Fixes some issues with GTTA spammers, makes the network faster as well
It builds, huray, what a suprise
=> Force depth 0

src/main/java/com/iota/iri/network/pipeline/TransactionProcessingPipelineImpl.java
Resolves a syncing problem by using a linked blocking queue
Fixes #1742 
Replaces #1833 which was merged to another branch
IRI was synced without needing to restart and no error appeared
It should be noted that I did notice a slow down in syncing
I think we should investigate going back to array based queues later on to speed things up
Make sure to provide instructions for the maintainer as well as any relevant configurations.
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.
=> Use LinkedBlockingQueue to fix sync problems

src/main/java/com/iota/iri/network/pipeline/MilestoneStage.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java, src/test/java/com/iota/iri/network/pipeline/MilestoneStageTest.java
The addition of the milestone stage and consolidation of milestone logic has resulted in a couple of small bugs that need patching before we merge with dev. 
The first is that milestones were being registered in the milestone stage, which meant that the latest milestone object would be updated prior to validation. Removing this from the milestone stage fixes that issue. 
Secondly the thread did not have a sleep timer at all, and it was eating up more cpu and memory than necessary. A 500 millisecond sleep mitigates this issue without damaging performance. 
Thirdly I added a couple of additional logs to improve understanding of the code. 
- Bug Fix
Ran nodes on an internal test network and profiled them to make sure they worked, and didn't overload the cpu as much.
=> Logs and bug patches for milestone solidification 

src/main/java/com/iota/iri/network/pipeline/MilestoneStage.java, src/main/java/com/iota/iri/network/pipeline/ReceivedStage.java, src/main/java/com/iota/iri/service/milestone/MilestoneRepairer.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneRepairerImpl.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java, src/main/java/com/iota/iri/service/validation/impl/TransactionSolidifierImpl.java
After removing the cache with the dev branch merge, the propagation process takes a little longer to complete, and holds up the transaction solidifier processing time. To mitigate this, the propagation queue will be processed in batches to avoid the issue of holding up transactions in the solidification queue from being processed. Also, a small bug fix to the milestone solidifier to make sure we are registering new milestones that are not solid but valid.  
Tests that failed the merge into dev are passing now.
=> Fix: max propagate up to 10 transactions for solidification

src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java
When making the change in 1845, the registration of milestones was placed into the `addSeenMilestones` method which is only called once a milestone is valid AND solid. Failing to register new milestones on validity regardless of solidity causes an error that flies under the radar with the regression test setup. We need to register and log the new milestones as they get validated, otherwise the solidification process never kicks off. This part of the logic is no different from the previous implementation with the `LatestMileStoneTracker` and shouldn't be changed. 
Tests all passed on the last version and didn't catch this bug. Throwing it up onto the ICC and testing it there has allowed me to catch it in the act, and determine the …
=> Fix: Milestone solidifier log milestone on validity not solidity

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
Changes code to use a more lightweight entrypoint generation.
Code largely based on Hornet LS code, thanks <3
fixes #1797
base branch should be changed, code is currently based on 1.8.5 as requested
Takes snapshot, runs unit tests.
Test: 
https://github.com/kwek20/random-tests/blob/master/src/main/java/org/iota/test/tests/TestSnapshot.java
Todo: 
- ~~Private net tests~~ 
- 
- More broad tests with team
=> [Fix] LS taking too long

src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java, src/main/java/com/iota/iri/service/validation/impl/TransactionSolidifierImpl.java
Milestone bootstrapping in the solidifier was registering solid milestones before the snapshot provider, and therefore the milestones were not being applied correctly. This caused a discrepancy between the `getNodeInfo` latest solid milestone vs the `MilestoneSolidifier` latest solid milestone. It also stopped milestone candidates that were between these 2 separate values from being properly processed. The change here ensures that any valid and incomplete milestone candidates are properly placed into the queue for processing.
As an addition the `updateQueues()` method has been removed as it is unnecessary logic. 
Choose a type of change, and delete any options that are not relevant.
Canary has been syncing continuously on Mainnet from …
=> Update milestone bootstrapping

src/main/java/com/iota/iri/service/validation/impl/TransactionSolidifierImpl.java
The `TransactionSolidifier` has a set value of 50k transactions for analyzed hashes as legacy from the previous milestone logic. With high tps environments it's possible for this low threshold to be reached between milestones and slow or stall out synchronisation. To accommodate this the max value should be increased to 300k minimum to account for the possibility of a 1000TPS environment with a 30 second tick rate for compass. 
Less false returns for solidification as a result of the maximum capacity of analyzed transactions being reached.
=> Update queue size for solidifier

src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java
Logging of the progressbar didnt occur as we use an interval logger, and another message takes priority.
Now we have 4 intervalloggers :D
Ran it on le node, no spam from logging anymore!
=> Change: add interval loggers

src/main/java/com/iota/iri/conf/SnapshotConfig.java
Added explanation of default suffix for `LOCAL_SNAPSHOTS_DB_MAX_SIZE ` param
=> Added explanation of default suffix for DB size

src/main/java/com/iota/iri/MainInjectionConfiguration.java, src/main/java/com/iota/iri/network/NetworkInjectionConfiguration.java, src/main/java/com/iota/iri/network/pipeline/BroadcastStage.java, src/main/java/com/iota/iri/network/pipeline/TransactionProcessingPipelineImpl.java, src/main/java/com/iota/iri/service/milestone/InSyncService.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneInSyncService.java, src/main/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImpl.java, src/test/java/com/iota/iri/network/NetworkInjectionConfigurationTest.java, src/test/java/com/iota/iri/network/pipeline/BroadcastStageTest.java, src/test/java/com/iota/iri/network/pipeline/TransactionProcessingPipelineTest.java, src/test/java/com/iota/iri/service/milestone/impl/MilestoneInSyncServiceTest.java, src/test/java/com/iota/iri/service/snapshot/impl/LocalSnapshotManagerImplTest.java
Extracts our sync checker to a service, and uses that service in the BroadcastStage of the Network pipeline.
This is required because if you get all your new transactions from 1 neighbour, and have 1 other neighbour which doesnt have the transaction you need, there is no chance of syncing.
If that second neighbour sends you a very low amount of new transactions(compared to the other neighbour) you will still sync, but very slow.
This has been introduced due to our removal of "ping pong" in #1745 
The stuck node got unstuck in the scenario described above
=> Feature: Sync check added to broadcast stage

src/main/java/com/iota/iri/MainInjectionConfiguration.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java, src/main/java/com/iota/iri/service/validation/impl/TransactionSolidifierImpl.java, src/test/java/com/iota/iri/service/validation/impl/TransactionSolidifierImplTest.java
If a sync is midway through and the node is shut off, it's possible for milestone transactions to get lost in the mix on restart. The transaction object may be present but the milestone object has not been generated. This means that if the node tries to solidify a transaction that references this milestone, it will always skip requesting this transaction as it is already stored. 
This stops the milestones from making it into the solidification queue again. By making the `TransactionSolidifier` request milestones regardless of solidity, and adding an address scanning method for when synchronization stalls out on reboot, we can mitigate most issues that would pop up revolving around syncing and restarting during a sync. 
Also lowers the max size of the `TransactionSolidifier` processing …
=> Fix milestone solidification on reboot

src/main/java/com/iota/iri/network/NeighborRouterImpl.java, src/main/java/com/iota/iri/network/neighbor/Neighbor.java, src/main/java/com/iota/iri/network/neighbor/impl/NeighborImpl.java, src/test/java/com/iota/iri/network/neighbor/impl/NeighborImplTest.java
Tries to solve the syncing problem from #1863 by synchronizing between registering of operation to keys, to ensure no race conditions...
It was ran w.o. data races and no noticeable sync slow down
=> Fix: resolve race in networking layer assigning write operation to key
