iotaledger/iri

src/main/java/com/iota/iri/service/API.java
=> better to check if loopback address

README.md, changelog.txt, dependency-reduced-pom.xml, pom.xml, src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/IXI.java, src/main/java/com/iota/iri/Milestone.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/hash/PearlDiver.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/CallableRequest.java, src/main/java/com/iota/iri/service/Node.java, src/main/java/com/iota/iri/service/TipsManager.java, src/main/java/com/iota/iri/service/storage/StorageScratchpad.java
Merged with dev branch. Made corrections to TipManager. Added mixed strategy feature
=> Testnet update from dev. Bug fixes.

README.md, dependency-reduced-pom.xml, pom.xml, src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/Milestone.java, src/main/java/com/iota/iri/Neighbor.java, src/main/java/com/iota/iri/model/Transaction.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/Node.java, src/main/java/com/iota/iri/service/TipsManager.java, src/main/java/com/iota/iri/service/dto/ExportToExternalDBResponse.java, src/main/java/com/iota/iri/service/storage/Replicator.java, src/main/java/com/iota/iri/service/storage/ReplicatorSinkPool.java, src/main/java/com/iota/iri/service/storage/ReplicatorSinkProcessor.java, src/main/java/com/iota/iri/service/storage/ReplicatorSourcePool.java, src/main/java/com/iota/iri/service/storage/ReplicatorSourceProcessor.java
1.1.3.0 with TCP/IP replicator
=> 1.1.3.0 with TCP/IP replicator

pom.xml, src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/service/tangle/rocksDB/RocksDBPersistenceProvider.java
Create an ini file iota.ini (or whatever you like), and put the values you need in it. Example:
```
[IRI]
API_PORT = 14700
NEIGHBORS = udp://my.neighbor.one:12345 tcp://my.second.neighbor:12345
```
=> added config file option

src/main/java/com/iota/iri/service/TipsManager.java, src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java, src/test/java/com/iota/iri/service/TipsManagerTest.java
Square root weight
Non-recursing rating update
=> Rating hotfix

src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/Milestone.java, src/main/java/com/iota/iri/service/TipsManager.java
moved rescan away from milestone loop, and set thread to sleep up to milestone rescan interval, but not longer
=> Updated milestone scan loop

src/main/java/com/iota/iri/LedgerValidator.java, src/main/java/com/iota/iri/controllers/TipsViewModel.java, src/main/java/com/iota/iri/controllers/TransactionRequester.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/model/Hash.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/network/UDPReceiver.java, src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java, src/main/java/com/iota/iri/service/TipsManager.java, src/main/java/com/iota/iri/storage/FileExportProvider.java, src/test/java/com/iota/iri/model/HashTest.java, src/test/java/com/iota/iri/service/TipsManagerTest.java
In preparation for merging testnet-rework branch
=> Reverted to 3774a2f

src/main/java/com/iota/iri/LedgerValidator.java, src/main/java/com/iota/iri/hash/PearlDiver.java
runtime improvement - Curl align truth-table for transform()
runtime improvement - PearlDiver better branch prediction
=> runtime improvement - Curl & PearlDiver

src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java
Changed "Transdaction" to "Transaction".
=> Fixes iotaledger/iri#171

src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/TipsManager.java
I've added a tie-breaker as well as a user-configurable minimum number of iterations for tip selection.
=> MCMC update

src/main/java/com/iota/iri/service/TipsManager.java
fixed belowMaxDepth tip checked
look for depth based on solid subtangle
=> re-enable maxDepth checks

README.md
=> updated readme doc

src/main/java/com/iota/iri/controllers/MilestoneViewModel.java
=> allow fetching first milestone, also when MILESTONE_START_INDEX != 0

src/test/java/com/iota/iri/controllers/MilestoneViewModelTest.java
Latest merge to MilestonViewModel broke tests. This PR fixes it.
=> Updated Milestone Test to latest changes

README.md
not sure if that is the correct fix, but reads better
=> wording fix-up

src/main/java/com/iota/iri/Milestone.java, src/main/java/com/iota/iri/Snapshot.java, src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/network/TransactionRequester.java, src/test/java/com/iota/iri/TransactionValidatorTest.java
Adjustments for mwm 9. Took snapshot from public testnet 1.3.1.
=> Public testnet 1.4.0

.travis.yml, changelog.txt, pom.xml, src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/service/API.java
=> Add X-IOTA-API-Version to CORS allowed headers

Dockerfile
=> fixed iri version in dockerfile

src/main/java/com/iota/iri/Milestone.java, src/main/java/com/iota/iri/Snapshot.java, src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/network/TransactionRequester.java, src/test/java/com/iota/iri/TransactionValidatorTest.java
MWM 9 and initial milestone/timestamp adjustments. Snapshot from previous public testnet.
=> Public testnet 1.4.1.1

src/main/java/com/iota/iri/Milestone.java, src/main/java/com/iota/iri/Snapshot.java, src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/conf/Configuration.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/network/TransactionRequester.java, src/test/java/com/iota/iri/TransactionValidatorTest.java
Timestamp threshold is 10/28/2017 @ 1:00pm (UTC)
=> Adjustments for mwmw 9, milestone start indes 320200, timestamp threshold.

src/main/java/com/iota/iri/service/API.java
=> always have info field, even when no information is present

src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/TipsManager.java
=> TransactionsToApprove - unset reference if transaction is deeper than depth 

src/main/java/com/iota/iri/service/API.java
This PR fixes #463 #368 #275 #147 :sweat_smile: 
**duplicate hashes:**
1. L630: the use of `indexOf` would always change the first copy
2. `exhaustiveSearchWithinIndex` `counter` arg was the size of a `set` - `sameIndexTransactions`, so it would stop before done.
**null pointer:**
L661: if there is no tip at the corresponding index, the `nonAnalyzedTransactions` arg would be `null`, so `exhaustiveSearchWithinIndex` would `poll` a null queue
=> fix getInclusionStates for duplicates and null pointer

src/main/java/com/iota/iri/service/TipsManager.java
update visitedHashes & diff with selected tip's view - resolves #527
=> TipSelection - reduce "inconsistent tips pair selected" by having second walker aware of first walker's PoV

pom.xml
This fixes some of the ZeroMQ issues that people were facing.
=> bump jeromq to 0.4.3

README.md
Replace Slack link with Discord link. Add IOTA forum link.
=> Update README: Replace Slack with Discord

src/main/java/com/iota/iri/model/Hash.java
Equals shouldn't never throw an AssertionError.
=> fix equals() in hash

src/main/java/com/iota/iri/storage/FileExportProvider.java
=> Closed PrintWriter resource which is not closed.

src/main/java/com/iota/iri/service/ValidationException.java
ValidationException fix of typos.
=> Fixed typos at ValidationException.

iota-checks.xml, pom.xml, src/main/java/com/iota/iri/BundleValidator.java, src/main/java/com/iota/iri/IXI.java, src/main/java/com/iota/iri/LedgerValidator.java, src/main/java/com/iota/iri/hash/Kerl.java, src/main/java/com/iota/iri/model/Hash.java, src/main/java/com/iota/iri/network/Neighbor.java, src/main/java/com/iota/iri/network/replicator/ReplicatorSinkProcessor.java, src/main/java/com/iota/iri/network/replicator/ReplicatorSourceProcessor.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/TipsManager.java, src/main/java/com/iota/iri/storage/Tangle.java, src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java, src/main/java/com/iota/iri/utils/Serializer.java
This will cause Travis CI to fail due to checkstyle errors enforced by the rules in `iota-checks.xml`.
Currently only braces around code blocks are enforced (see http://checkstyle.sourceforge.net/config_blocks.html#NeedBraces).
Rules will be added incrementally.
Note that `mvn site` will still create a checkstyle report using the default `sun-checks.xml`. This is because the report with `iota-checks.xml` will  always be empty on successful builds. If we think the report is redundant we can remove it.
=> Checkstyle will fail build

README.md
You don't publish ports if `--net=host` (`--network=host`) is used
Please include a summary of the change. Include the motivation for the change.
Please delete options that are not relevant.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Docker: useless `-p` (publish)

src/main/java/com/iota/iri/controllers/TipsViewModel.java
- Fixed Generic Type to remove infraction warning during  build.
- Tightened access modifiers.
- Made cache private class with final properties
- Removed unused returns in 2 methods.
(access can be broadened in the future if needed again)
=> TipsViewModel.java minor edits

.github/pull_request_template.md
=> formatting, fixed grammer

src/main/java/com/iota/iri/zmq/MessageQ.java
gracefully shutdown ZMQ, also when not enabled - Avoids null exception on shutdown.
ZMQ publisher and context are only initialized if `ZMQ_ENABLED == True`, so when stopping a node w/o ZMQ a null exception occurs:
```java
04/03 16:48:43.167 [Shutdown Hook] ERROR com.iota.iri.IRI - Exception occurred shutting down IOTA node: 
java.lang.NullPointerException: null
at com.iota.iri.zmq.MessageQ.shutdown(MessageQ.java:54) ~[classes/:na]
at com.iota.iri.Iota.shutdown(Iota.java:179) ~[classes/:na]
at com.iota.iri.IRI.lambda$shutdownHook$0(IRI.java:247) ~[classes/:na]
at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
```
this PR fixes it.
- Bug fix (non-breaking change which fixes an issue)
Compared `dev` to PR as regression, starting a local node and shutting down.
=> gracefully shutdown ZMQ

.gitignore
An extension of #523 
Ignores files that can sometimes be created by the OS but shouldn't be committed
=> Add Mac, Linux, and Windows files to gitignore

src/main/java/com/iota/iri/controllers/TransactionViewModel.java
We should only persist an update to disk if data actually changed.
=> Reduce writes if no data changed.

README.md
Adds `README.md` status badges, like:
- build status
- code quality
- test coverage
- latest release version
- license
this has 2 goals:
1. give more information about the project's progress
2. encourage people to contribute so that code quality and coverage will rise
=> Add readme repo status badges

src/main/java/com/iota/iri/storage/ZmqPublishProvider.java
Add Tag value to the ZMQ `tx` topic. 
see discussion in #540 for more details.
- select stakeholders tested ZMQ clients to see no issues arise from change (see original PR)
=> Added getTagValue to ZMQ tx topic (alon-e rework of #540)

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/SignedFiles.java, src/main/java/com/iota/iri/Snapshot.java, src/main/java/com/iota/iri/service/API.java, src/test/java/com/iota/iri/SnapshotTest.java
- Cleaned up isFileSignatureValid and isFileSignatureValid.
- Streamlined reader and IO setup.
- Removed local exception conversion.
- Added throws to dependent classes.
=> Edit SignedFiles.java

pom.xml
Auto formatting the pom file.
No code changed.
=> auto-format pom

README.md
(My git went berserk and committed a bunch of other files with the last PR of this. This replaces that one.)
Reworded a bit
Changed ports in chart to reflect typical setup conditions.
Added API getting started link
Added a little more detail in command line
Added short explainer about friending within the network
=> edit readme (replaces old)

.travis.yml, Dockerfile, changelog.txt, pom.xml, src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/controllers/TagViewModel.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/model/ObsoleteTag.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java, src/test/java/com/iota/iri/integration/APIIntegrationTests.java
incorporates:
Tag indexing - #728
Version bump to v1.4.2.4_RC
=> V1.4.2.4_RC changes into dev

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/controllers/TagViewModel.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/model/ObsoleteTag.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/storage/rocksDB/RocksDBPersistenceProvider.java, src/test/java/com/iota/iri/integration/APIIntegrationTests.java
Use the Tag field when finding transaction via API.
Fixes #726 (also #340, #611, #606)
**This PR requires a DB migration to function properly, and is planned to be added to the next version**
- Added regression test to APIIntegrationTests that fetches using both Tag versions
=> Use the Tag field when finding transaction via API.

src/main/java/com/iota/iri/IRI.java, src/main/java/com/iota/iri/conf/Configuration.java
=> Revert "Check ini file before loading default testnet values and add testnetdb flag"

.travis.yml
Travis now merges incoming PR with `dev` and runs the following tests:
1. Starting and stopping a node without a database in testnet/mainnet mode
2. Starting and stopping a node in testnet mode with a database and asserting solidity of latest milestone
3. Sending a transaction on one node and asserting that another node received it.
Travis was ran in private repository and passed. Regression tests worked on local machine.
=> make travis run integration tests after merge

.travis.yml
Just setting Travis to run mvn with -Dlogging-level=INFO
=> Travis should run mvn on info level 

src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
unit tests for `WalkerValidatorImpl`
unit tests have passed.
=> walker validator impl test

DOCKER.md, README.md, changelog.txt, pom.xml, src/main/java/com/iota/iri/IRI.java
=> version bump v1.5.0

DOCKER.md, changelog.txt, pom.xml, src/main/java/com/iota/iri/IRI.java
=> version bump v1.5.2

DOCKER.md, changelog.txt, pom.xml, src/main/java/com/iota/iri/IRI.java
=> version bump v1.5.3

src/main/java/com/iota/iri/TransactionValidator.java
=> move sleep inside spawnSolidTransactionsPropagation loop

.github/issue_template.md
Fixes minor issues with the issue template
Not applicable
=> Fix minor issues with issue template

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
Milestone start index default value is incorrect
Fixes synchronization issue.
Ran by @hmoog on a canary
=> Fix milestone start index default value

.gitignore
Removes the folders generated by running the node on Eclipse
Enhancement (a non-breaking change which adds functionality)
=> Git ignore eclipse files

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/LedgerValidator.java, src/main/java/com/iota/iri/MilestoneTracker.java, src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java, src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/WalkValidatorImplTest.java
Renamed Milestone class to MilestoneTracker to better reflect its functionality and to ease the review of future PR's since Local Snapshots uses MilestoneTracker in its codebase.
Should be reviewed an approved as fast as possible to make future PR's easier to check (otherwise it doesnt show the diffs but all changes as a new file).
=> Feat: renamed Milestone to MilestoneTracker

ruleset.xml
Replaces #988
Adds pmd rules to be used by codacy.
Pmd has been run with this ruleset
=> add pmd ruleset

src/main/java/com/iota/iri/IXI.java
This are some minor code cleanup on IXI.java
mvn clean install
=> Cleanup: Some minor code cleanup on IXI.java

src/main/java/com/iota/iri/network/TCPNeighbor.java
As mentioned by static analysis tools - there are missing parameters in these 2 places:
https://sonarcloud.io/project/issues?id=alon-e_iri&issues=AWZT3V5SBfefbO9Hm7SP&open=AWZT3V5SBfefbO9Hm7SP
https://app.codacy.com/app/iotaledger/iri/file/23686352764/issues/source?bid=6391906&fileBranchId=6391906#l53
=> add missing parameter to log statement

src/main/java/com/iota/iri/model/HashFactory.java
fixes a reference in the javadocs
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_
- Building javaDocs - use to give a warning
=> javadocs param fix

STYLEGUIDE.md
Just expanded the documentation section in the guideline
=> Documentation explanation in styleguide

src/main/java/com/iota/iri/crypto/Curl.java, src/main/java/com/iota/iri/crypto/ISS.java, src/main/java/com/iota/iri/crypto/ISSInPlace.java, src/main/java/com/iota/iri/crypto/Kerl.java, src/main/java/com/iota/iri/crypto/PearlDiver.java, src/main/java/com/iota/iri/crypto/Sponge.java, src/main/java/com/iota/iri/crypto/SpongeFactory.java
Document hash functions, PoW calc, and signature scheme.
Fixes #1112 
generating JavaDocs locally.
=> Document crypto package

src/main/java/com/iota/iri/network/Node.java, src/main/java/com/iota/iri/network/TCPNeighbor.java, src/main/java/com/iota/iri/network/UDPNeighbor.java, src/main/java/com/iota/iri/network/replicator/Replicator.java
Added code comments for networking part. 
iotaledger/iri#1105
Unit test
=> Added documentation for networking

DOCKER.md, pom.xml, src/main/java/com/iota/iri/IRI.java
Bumps version for release candidate.
From now on every change to `dev-localsnapshot` should cause a version bump.
=> bump version to 1.6.0-RC1

src/main/java/com/iota/iri/service/tipselection/EntryPointSelector.java, src/main/java/com/iota/iri/service/tipselection/RatingCalculator.java, src/main/java/com/iota/iri/service/tipselection/TailFinder.java, src/main/java/com/iota/iri/service/tipselection/TipSelector.java, src/main/java/com/iota/iri/service/tipselection/WalkValidator.java, src/main/java/com/iota/iri/service/tipselection/Walker.java, src/main/java/com/iota/iri/service/tipselection/impl/CumulativeWeightCalculator.java, src/main/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/RatingOne.java, src/main/java/com/iota/iri/service/tipselection/impl/TailFinderImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/TipSelectorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkValidatorImpl.java, src/main/java/com/iota/iri/service/tipselection/impl/WalkerAlpha.java
tweak tip selection documentation.
Fixes #1119 
=> tweak tip selection documentation.

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
This PR introduces a method to limit the milestones that have to be analyzed when generating the solid entry points.
Since the snapshot creation is a "continuous" process where we build upon the information gathered during the creation of previous snapshots, we do not need to analyze all previous milestones but can rely on slowly gathering the missing information over time. While this might lead to a situation where the very first snapshots taken by a node might generate snapshot files that can not reliably be used by other nodes to sync it is still a reasonable trade-off to reduce the load on the nodes. We just assume that anybody who wants to share his snapshots with the community as a way to bootstrap new nodes will run his snapshot enabled node for a few hours before sharing his files …
=> Perf: Limit the amount of milestones that need to be analyzed when generating the solid entry points

src/main/java/com/iota/iri/Iota.java, src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
This PR completely disables the creation of the snapshot related managers and classes if the features are disabled in the config.
=> Feat: Disable snapshot logic completely if disabled in the config

src/main/java/com/iota/iri/controllers/AddressViewModel.java, src/main/java/com/iota/iri/controllers/ApproveeViewModel.java, src/main/java/com/iota/iri/controllers/BundleViewModel.java, src/main/java/com/iota/iri/controllers/TagViewModel.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/model/AbstractHash.java, src/main/java/com/iota/iri/model/AddressHash.java, src/main/java/com/iota/iri/model/BundleHash.java, src/main/java/com/iota/iri/model/TagHash.java, src/main/java/com/iota/iri/model/TransactionHash.java, src/test/java/com/iota/iri/controllers/BundleViewModelTest.java, src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
fix `first()` calls in view models, a regression introduced in Hash refactoring.
Fixes #1176 
- Added unit (regression) tests, which fail on current `dev` but pass with fixes.
=> fix first() calls in view models

src/main/java/com/iota/iri/service/API.java, src/test/java/com/iota/iri/service/APIIntegrationTests.java, src/test/java/com/iota/iri/utils/MapIdentityManagerTest.java
Posting invalid json to IRI will result in detailed error message.
Fixes #1201 
- Added integration test to APIIntegrationTests
- run mvn clean install
=> Fixed #1201: Posting invalid json to IRI will result in detailed error message

src/main/java/com/iota/iri/service/API.java
Fixes #1185
- running an isolated node
- running a local network
=> make storeMessage store transactions

pom.xml
Upgrade jackson dependency to obtain latest security fixes
Automated regression tests are sufficient for this type of change
=> Up jackson to version 2.9.8

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotStateImpl.java
Change log level to debug when reporting on an inconsistent address
=> Fix: log inconsistent addresses in debug mode

python-regression/tests/features/machine2/config.yml
Python regression test fix - machine 2
Not been tested.
=> Python-reg-test fix machine2

python-regression/tests/features/machine1/config.yml, python-regression/tests/features/machine2/config.yml, python-regression/tests/features/machine3/config.yml, python-regression/tests/features/machine4/config.yml, python-regression/tests/features/machine5/config.yml
Adding jacoco agent to TIAB config files used in python regression tests.
Configuration changes
=> Added jacoco agent with java_options

src/main/java/com/iota/iri/conf/BaseIotaConfig.java
Fixes #1467 
Pruning stopped occuring by default
=> Change: Pruning is now off by default

src/main/java/com/iota/iri/service/milestone/impl/LatestMilestoneTrackerImpl.java, src/main/java/com/iota/iri/service/milestone/impl/MilestoneServiceImpl.java
Fixes an IndexOutOfBoundsException occurring in the MilestoneServiceImpl.
https://github.com/iotaledger/iri/issues/1477
Private net.
=> Fix: Prevents IndexOutOfBoundsException within the MilestoneServiceImpl

.github/ISSUE_TEMPLATE/bug_report.md
Updates bug report template with new Discord links
N/A
=> Update bug report template with new Discord links

src/test/java/com/iota/iri/crypto/ISSTest.java
Add a unit test for ISSInPlace.digest. This function is used in bundle validation. It also serves the purpose of reference test implementation for cIRI.
=> create ISSInPlace.digest test case for cIRI as reference

pom.xml
Updating dependencies to have the latest features
Update undertow to 2.0.22
Update jackson-databind to 2.9.9
The changes affect how we may read from the configuration file and the API.
Automatic regression and unit tests cover that the configuration.
If they pass, it is all that needed.
=> Update undertow and jackson

README.md
=> Fix: Updated discord link

src/test/java/com/iota/iri/TransactionTestUtils.java, src/test/java/com/iota/iri/benchmarks/crypto/CurlBenchmark.java, src/test/java/com/iota/iri/controllers/MilestoneViewModelTest.java, src/test/java/com/iota/iri/crypto/CurlTest.java, src/test/java/com/iota/iri/crypto/KerlTest.java, src/test/java/com/iota/iri/service/APIIntegrationTests.java, src/test/java/com/iota/iri/service/ledger/impl/LedgerServiceImplTest.java, src/test/java/com/iota/iri/utils/TestSerializer.java
We had some pmd errors on our test files. Not anymore!
- its a change.
=> Change: Fixed pmd test errors

README.md
Update links in README.md to the correct docs.iota.org pages.
Fixes #1559
=> Updated links to official documentation

src/main/java/com/iota/iri/storage/Indexable.java, src/main/java/com/iota/iri/storage/Persistable.java
Document Persistable and Indexable
Fixes #1157 
=> Document Persistable and Indexable

README.md
Correct simple typos in the readme
=> Correct typos in the README.md

src/main/java/com/iota/iri/IRI.java
Perhaps it did not reflect this after `docs.iota.org` was reorganized.
_Please include a summary of the change. Include the motivation for the change._
_Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration_
- Test A
- Test B
=> Fix broken link of online documentation

.gitignore, README.md
This pull request changes value for DB_PATH in README.md to default value for this field. Also, .factorypath is added to .gitignore (auto-generated when using VSCode). Since these two changes are very small, I added them in the single pull request.
Fixes #262, #1181 
Nothing to test.
=> DB_PATH changed in README.md, .factorypath added to .gitignore

pom.xml
updated the jdeb plugin to the latest one i.e, 1.8
=> Update jdeb plugin

pom.xml
Updated RocksDB to 6.3.6
Fixes #1629
=> Updated RocksDB to 6.3.6

pom.xml
Replaces #1662 
All unit and regression tests passed
=> Bump Jackson Databind to 2.9.10.1

src/main/java/com/iota/iri/TransactionValidator.java, src/main/java/com/iota/iri/service/API.java
Improve API error response for storeTransactions
Fixes #1679 
- Bugfix (a non-breaking change which fixes an issue)
All existing unit tests pass
=> improve API error response for storeTransactions

python-regression/util/test_logic/api_test_logic.py, src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/main/java/com/iota/iri/controllers/ApproveeViewModel.java, src/main/java/com/iota/iri/controllers/MilestoneViewModel.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/service/transactionpruning/jobs/MilestonePrunerJob.java
=> Added checks to make cache more robust

python-regression/util/test_logic/api_test_logic.py, src/main/java/com/iota/iri/cache/Cache.java, src/main/java/com/iota/iri/cache/CacheConfiguration.java, src/main/java/com/iota/iri/cache/CacheManager.java, src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/main/java/com/iota/iri/cache/impl/DefaultCacheConfiguration.java, src/main/java/com/iota/iri/cache/impl/MilestoneCacheConfiguration.java, src/main/java/com/iota/iri/controllers/ApproveeViewModel.java, src/main/java/com/iota/iri/controllers/MilestoneViewModel.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/service/transactionpruning/jobs/MilestonePrunerJob.java, src/main/java/com/iota/iri/service/transactionpruning/jobs/UnconfirmedSubtanglePrunerJob.java, src/main/java/com/iota/iri/storage/Tangle.java, src/test/java/com/iota/iri/cache/CacheTest.java, src/test/java/com/iota/iri/service/milestone/impl/MilestoneServiceImplTest.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImplTest.java, src/test/java/com/iota/iri/service/tipselection/impl/EntryPointSelectorImplTest.java
A set of fixes/improvements following review iteration
- Upgrade regression test exception syntax from Python 2 to Python 3
- Refactoring
- Added measures to make sure data is not lost in the cache without having been saved in DB.
- New and existing unit tests pass
=> Cache optimisations and refactoring

src/main/java/com/iota/iri/controllers/TransactionViewModel.java, src/main/java/com/iota/iri/storage/Tangle.java
Publish tx zmq topic after a transaction is updated.
Fixes #1727 
- Existing tests pass
=> publish tx to zmq on tvm.update

src/test/java/com/iota/iri/controllers/TransactionViewModelTest.java
Added unit tests to cover tx delete scenarios with cache.
Part of #1734 
- New and existing unit tests pass
=> Added TVM cache delete tests

python-regression/tests/features/machine2/2_transaction_tests.feature, python-regression/tests/features/steps/api_test_steps.py, python-regression/tests/features/steps/local_snapshots_steps.py, python-regression/tests/features/steps/response_handling_steps.py, python-regression/tests/features/steps/transaction_steps.py, python-regression/util/logger.py, python-regression/util/milestone_logic/milestones.py, python-regression/util/neighbor_logic/neighbor_logic.py, python-regression/util/response_logic/response_handling.py, python-regression/util/test_logic/api_test_logic.py, python-regression/util/threading_logic/pool_logic.py, python-regression/util/transaction_bundle_logic/transaction_logic.py
Our machine2 regression test fails one in ~~20 on buildkite.
After testing this locally for about 50x, we decided it is likely a race condition between buildkite and the node.
We increase the milestone wait time by 5 seconds and see if it ever fails again
Ran the test a quazillion times,  fresh db every time
=> Fix: machine2 regression test on buildkite

python-regression/tests/features/machine1/1_api_tests.feature, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java, src/test/java/com/iota/iri/service/APIIntegrationTests.java
As requested in https://github.com/iotaledger/iri/issues/1449#issuecomment-491787435, i have added the estimated db size to the reply of `getNodeInfo` 
Also added `coordinatorAddress` and  `features` to the unit test (They were missing)
=> Feature: DB size to getNodeInfo

src/main/java/com/iota/iri/service/transactionpruning/SizePruningCondition.java
Remove the log indicating the preferred pruning depth, as they work separate of each other now.
=> Logging: Removed pruning suggestion

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotProviderImpl.java
#Description
Makes the message you receive when you (likely) use an old db structure more usefull
Fixes #1749
=> Logging: Changed missing local snapshot message

README.md
Removes references to JavaScript.
=> Documentation: Removes references to JavaScript

src/main/java/com/iota/iri/cache/Cache.java, src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/test/java/com/iota/iri/cache/CacheTest.java
Remove unused `cache.release()`
=> Removed unused cache.release

src/main/java/com/iota/iri/zmq/README.md, src/main/java/com/iota/iri/zmq/ZmqMessageQueueProvider.java
Renames zmq `tx_trytes` topic to `trytes`
Fixes #741 
- More tests pending here: https://github.com/iotaledger/iri/pull/1730
=> rename zmq tx_trytes to trytes

src/main/java/com/iota/iri/service/dto/GetNodeInfoResponse.java
Better documentation for milestone index that we produce automatically
Just doc fix, a review should suffice
=> Documentation: Description for milestone start index

src/main/java/com/iota/iri/service/Feature.java
This adds a feature "WereAddressesSpentFrom" in "getNodeInfo"
Fixes #1779 
This has not been tested/compiled.
=> Add feature were addresses spent from

python-regression/tests/features/machine1/1_api_tests.feature, src/main/java/com/iota/iri/service/API.java, src/main/java/com/iota/iri/service/ApiCommand.java, src/test/java/com/iota/iri/service/APIIntegrationTests.java
Remove the get tips api call
Fixes #1615 
We removed a call and existing tests must be removed in order for the build to pass
=> Delete get tips

python-regression/tests/features/steps/api_test_steps.py, python-regression/tests/features/steps/local_snapshots_steps.py, python-regression/tests/features/steps/response_handling_steps.py, python-regression/tests/features/steps/transaction_steps.py, python-regression/util/logger.py, python-regression/util/milestone_logic/milestones.py, python-regression/util/neighbor_logic/neighbor_logic.py, python-regression/util/response_logic/response_handling.py, python-regression/util/test_logic/api_test_logic.py, python-regression/util/threading_logic/pool_logic.py, python-regression/util/transaction_bundle_logic/transaction_logic.py
Part of the #1646 breakdown. This updates the logging for regression tests to a new formatting. This will allow for better comparison between timing of test features and responses on the nodes. 
Fixes #1607 
Logs are properly formatted in regression tests
=> Update regression logging

src/main/java/com/iota/iri/cache/Cache.java, src/main/java/com/iota/iri/cache/impl/CacheImpl.java, src/main/java/com/iota/iri/controllers/TransactionViewModel.java
Ensures that only the saved key is released
Fixes #1816 
There are current unit tests.
I am suspecting that this caused solidification problem.
More tests should commence
=> Fix: release next key

src/main/java/com/iota/iri/network/neighbor/Neighbor.java, src/main/java/com/iota/iri/network/neighbor/impl/NeighborImpl.java, src/main/java/com/iota/iri/network/protocol/Heartbeat.java, src/main/java/com/iota/iri/network/protocol/Protocol.java, src/main/java/com/iota/iri/network/protocol/ProtocolMessage.java, src/main/java/com/iota/iri/network/protocol/message/MessageReaderFactory.java, src/test/java/com/iota/iri/network/neighbor/impl/NeighborImplTest.java, src/test/java/com/iota/iri/network/protocol/ProtocolTest.java
Adds `heartbeat` to message protocol.
Fixes #1792 
- Added new tests
=> add heartbeat message

python-regression/tests/features/machine4/4_api_tests.feature
=> Removed threshold

src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java
We now are adding only tail transactions as possible milestone candidates to analyze
Unit and regression tests
Will continue to test for syncing issues with this PR
=> Only add tail milestone candidates

python-regression/tests/features/machine1/1_local_snapshots_tests.feature
=> Fix test delay prune

src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java
When a transaction fails to get applied to the ledger due to the need to correct some form of corruption in ledger state, we should not remove it from the seen milestones queue so that the attempts to reset the milestone don't stop. 
In ICC tests when milestone failed to solidify it continued to try to reset the corruption rather than trying once and removing it from the seen milestones queue.
=> Only remove seen milestone if applied to ledger

src/main/java/com/iota/iri/service/milestone/impl/MilestoneSolidifierImpl.java
Some tiny changes improving the readability
=> Fix: Small ms solidifier fixes

src/main/java/com/iota/iri/network/NeighborRouterImpl.java, src/main/java/com/iota/iri/network/neighbor/impl/NeighborImpl.java, src/test/java/com/iota/iri/network/neighbor/impl/NeighborImplTest.java
Replaces #1863 
See description there
Choose a type of change, and delete any options that are not relevant.
- Bug fix (a non-breaking change which fixes an issue
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.
=> Remove condition in send

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java
Change local snapshot depth for calculating Solid Entry Points to 50
TBD
Make sure to provide instructions for the maintainer as well as any relevant configurations.
Add an `x` to the boxes that are relevant to your changes, and delete any items that are not.
=> Change local snapshot depth for calculating Solid Entry Points to 50

src/main/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImpl.java, src/test/java/com/iota/iri/service/snapshot/impl/SnapshotServiceImplTest.java
Do not allow to replay milestones
Choose a type of change, and delete any options that are not relevant.
=> Do not skip milestones
